Adding Helper Tagets to `multichain-testing` Makefile
Agoric/Agoric pull request #10093
Opened 2024-09-16 11:26 UTC by amessbee

@Jovonni recommends devs to add these targets to `multichain-testing` Makefile to run/test [`dapp-orchestration-basics`](https://github.com/Agoric/dapp-orchestration-basics). If we find them useful, it would be nicer to have them here to being with.

Refs: [Relevant section in README of orca-dapp](https://github.com/Agoric/dapp-orchestration-basics/blob/main/README.md#multichain-testing-makefile-helpers).

2024-09-16 16:13 UTC, turadg requested changes
I don't agree that the Makefile should have all these commands. The targets of a Makefile should be idempotent. If we need some convenience commands for using this tooling, let's make scripts files. They're quite discoverable by `ls scripts`.

2024-09-16 16:13 UTC, turadg commented on multichain-testing/Makefile
> +	corepack enable
`make corepack-enable` has no value over `corepack enable`.

In general, I think we should get away from all these `.PHONY` targets. A makefile is for making. If we just want an inventory of commands, that's better in a `package.json` "scripts" list or just the documentation.

2024-09-16 16:13 UTC, turadg commented on multichain-testing/Makefile
> +all: setup install
this one seems worthwhile since it has setup and install dependencies. but I still think it would be better as a script in `scripts` because it's not idempotent. "Making" should be repeatable and have the same outcome.

2024-09-16 20:04 UTC, 0xpatrickdev requested changes
Appreciate the contribution. As @turadg mentioned, I think we only need to land some of this:

1. include `setup` in the `start` script or a new `all` script

2. Document `update client` flow when relayers get out of sync

2024-09-16 20:04 UTC, 0xpatrickdev commented on multichain-testing/Makefile
> +teardown: stop-forward stop clean delete
`stop` already calls `stop-forward` and `delete`, and  `clean` calls `stop`. This would be simplified to `teardown: clean` which is redundant.

2024-09-16 20:04 UTC, 0xpatrickdev commented on multichain-testing/Makefile
> +	corepack enable
+1. And I don't think we should use the Makefile for anything JS related either. 

Developers should also learn about `corepack` much earlier, from [getting-started>installing yarn](https://docs.agoric.com/guides/getting-started/#installing-yarn), and we shouldn't need to re-document it here.

2024-09-16 20:04 UTC, 0xpatrickdev commented on multichain-testing/Makefile
> +all: setup install
We have `make start` that does everything here except `setup`. The `wait-for-pods` command is also more robust than the `sleep`s here. 

`setup` only needs to be called in two scenarios:
1.  First time user who doesn't have the needed dependencies or an `agship` kind cluster
2. User chose to stop things with `make stop clean` instead of just `make stop`, so we need to recreate a kind cluster

A potential harm of including `setup` in the `start` or an `all` script is that it will fail if the user hasn't called make clean. This would suggest that we should amend `start` to `clean setup install...`

I am not sure what my ultimate opinion is here. I see benefit in adding `clean setup` to the current `all` script, but also see it adding extra overhead for non-first-time users.

2024-09-16 20:04 UTC, 0xpatrickdev commented on multichain-testing/Makefile
> +	kubectl exec -i hermes-agoric-osmosis-0 -c relayer -- hermes update client --host-chain agoriclocal --client 07-tendermint-1
I like that we have this at our disposal and @Jovonni figured out a solution for expired clients. I would prefer to see us document the pain point/symptoms in an FAQ section of the README and we could document the kubectl command there. There are 3 different relayer nodes and 6 different clients that could go out of sync and this only covers one of the scenarios.

This FAQ item would also mention that this typically only happens if the environment has been running for a long time (several hours?) and another path is simply restarting the service.

2024-09-20 07:49 UTC, amessbee commented
Thanks for the comments - agreed with most of them. Will close this now!

2024-09-20 07:49 UTC, closed without merging