chore: update config for MAINNET
Agoric/Agoric pull request #10323
Opened 2024-10-23 06:33 UTC by rabi-siddique

closes: #XXXX
refs: #XXXX

## Description

### Security Considerations

### Scaling Considerations

### Documentation Considerations

### Testing Considerations

### Upgrade Considerations

2024-10-23 19:18 UTC, dckc requested changes
keys should be names for MAIN

to close #10194 , let's finalize all the configs, please - a3p and devnet should have the respective gov4 and a total of 3 after rotation.

2024-10-23 19:18 UTC, dckc commented on packages/builders/scripts/inter-protocol/replace-electorate-core.js
> +      gov3: 'agoric1zayxg4e9vd0es9c9jlpt36qtth255txjp6a8yc',
The keys should be the names, not gov1 / gov2 / gov3.

https://github.com/Agoric/agoric-sdk/blob/e1baf4e7e8efaab527d7eadf7305281dac8656c9/packages/vm-config/decentral-main-vaults-config.json#L165-L171

2024-10-24 04:19 UTC, dckc approved these changes
I'd rather finish devnet and a3p configs in this pr, but I guess we can do it later

2024-10-24 04:23 UTC, rabi-siddique commented
> I'd rather finish devnet and a3p configs in this pr, but I guess we can do it later

Do we need to update the devnet config again? I think we made an update to it in https://github.com/Agoric/agoric-sdk/pull/10251

2024-10-24 10:45 UTC, merged