eslint-plugin for Agoric SDK
Agoric/Agoric pull request #10665
Opened 2024-12-10 17:31 UTC by turadg

- **feat: scaffold @agoric/eslint-plugin**
- **feat: Add eslint rule to enforce start function synchronous prelude**
- **fixup test of prelude**
- **fixup scaffold**
- **fixup prelude rule**
- **fixup scaffold**
- **fix: Resolve TypeScript errors in ESLint plugin with AST traversal improvements**
- **fix RuleTester import**
- **refactor: Fix stack overflow in start-function-prelude AST traversal**
- **fix: Update error reporting in start-function-prelude ESLint rule**
- **fix: Improve await expression detection in start-function-prelude rule**
- **fix: Improve await expression detection in ESLint rule using AST traversal**
- **refactor: Improve await expression detection in start function prelude rule**
- **fix: Refactor await expression detection in ESLint rule**
- **fix: Refactor AST traversal to prevent stack overflow in ESLint rule**

closes: #XXXX
refs: #XXXX

## Description

### Security Considerations

### Scaling Considerations

### Documentation Considerations

### Testing Considerations

### Upgrade Considerations

2025-11-07 22:56 UTC, mhofman requested changes
The change request is for the `.ts` files, which shouldn't get JSDoc comments. I suspect one case is a pre-existing incorrect `@satisfies` JSDoc, the other is for a `@see` which I'm not sure what the correct approach should be. In general, should this rule simply not apply to `.ts` files?

I am also concerned that using `@import` in files that declare ambient types will cause breakage, at least when `.d.ts` are generated and published.

Also, is there a rule to avoid duplicate `@import` comments with the same specifier? This seems to have created quite a few of those, and in general, I'd really like if we could lint to group multiple imports from the same file into a single directive. Not a blocker though.

2025-11-07 22:56 UTC, mhofman commented on packages/internal/src/types.ts
> + * @import {mustMatch} from '@endo/patterns';
This is incorrect in a `.ts` file.

2025-11-07 22:56 UTC, mhofman commented on packages/portfolio-contract/test/supports.ts
> + * @import {BaseChainInfo} from './orchestration-api.js';
This is incorrect in a `.ts` file.

2025-11-07 22:56 UTC, mhofman commented on packages/zoe/src/contracts/loan/types-ambient.js
> + */
This might change the semantics of the file into a "module" vs a script, and break the ambient declarations below.

2025-11-07 22:56 UTC, mhofman commented on packages/zoe/src/contracts/types-ambient.js
> + * @import {Invitation} from '../types-index.js';
This might change the semantics of the file into a "module" vs a script, and break the ambient declarations below.

2025-11-07 23:11 UTC, turadg commented on packages/zoe/src/contracts/loan/types-ambient.js
> + */
Good catch, it does. I meant to exclude `*-ambient.js`. But given how little broke, I'll see what `types-ambient.js` files can be removed.

I don't think we should try to maintain the ambients for consumer outside this repo. If CI here passes we're fine.

2025-11-11 01:33 UTC, mhofman approved these changes
This PR highlighted some preexisting `typeof` problems. I ended up opening https://github.com/Agoric/agoric-sdk/pull/12202 based on this to address. Feel free to incorporate in this PR, or land it after,

> is there a rule to avoid duplicate `@import` comments with the same specifier? This seems to have created quite a few of those, and in general, I'd really like if we could lint to group multiple imports from the same file into a single directive.

I created https://github.com/Agoric/agoric-sdk/issues/12203 for a possible follow up. This should probably be a separate rule anyway.

2025-11-11 01:33 UTC, mhofman commented on packages/inter-protocol/src/auction/auctionBook.js
> + * @param {import('@agoric/zoe/src/contractSupport/recorder.js').MakeRecorderKit} makeRecorderKit
Why keep the inline `import()` here?

2025-11-11 01:33 UTC, mhofman commented on packages/inter-protocol/test/auction/tools.js
> + *   auctioneer: Installation<auctioneerStart>;
FYI I'm really surprised we don't need to do a `typeof` before these `start` functions.

2025-11-11 01:33 UTC, mhofman commented on packages/eslint-plugin/tests/rules/group-jsdoc-imports.test.js
> + * @import {SnapStoreInternal} from './snapStore.js';
Out of curiosity, why place the `@import` in this block and not the other block that already contains an `@import` ?

2025-11-11 01:33 UTC, mhofman commented on packages/swing-store/src/assertComplete.js
> + */
A little strange to see the `@import` after the usage. I suspect because there is no preamble in this file?

2025-11-11 01:33 UTC, mhofman commented on packages/SwingSet/src/controller/controller.js
> + *   xsnapBundleData?: ReturnType<makeXsnapBundleData>,
I suspect we're missing a typeof here too. Not sure why we get no error.

2025-11-11 01:33 UTC, mhofman commented on packages/SwingSet/src/controller/controller.js
> - * @import {default} from '../kernel/kernel.js';
Out of curiosity, why revert these and go back to inline import?

2025-11-11 01:33 UTC, mhofman commented on packages/inter-protocol/test/smartWallet/oracle-integration.test.js
> +   * @type {Instance<start>}
Another case of `typeof` missing.

2025-11-11 01:33 UTC, mhofman commented on packages/pola-io/src/ambient/cmd.js
> + * @param {{ execFile?: any, defaultEnv?: import('../cmd.js').Environment }} [io]
We can probably keep this change.

2025-11-11 23:17 UTC, turadg commented on packages/SwingSet/src/controller/controller.js
> - * @import {default} from '../kernel/kernel.js';
the `default` doesn't work

2025-11-11 23:17 UTC, turadg commented on packages/eslint-plugin/tests/rules/group-jsdoc-imports.test.js
> + * @import {SnapStoreInternal} from './snapStore.js';
Just expedient

2025-11-11 23:33 UTC, mhofman commented on packages/SwingSet/src/controller/controller.js
> - * @import {default} from '../kernel/kernel.js';
Interesting that `default` is a problem with `@import`.

Why revert the other imports?

2025-11-11 23:36 UTC, mhofman commented
It seems the [latest changes](https://github.com/Agoric/agoric-sdk/compare/914772224e935663b337d1841688771553396e09..d25bc6979c7853945d1b219c4855303c73388c77) re-introduced `@import` in `packages/inter-protocol/src/vaultFactory/types-ambient.js` and reverted `typeof` changes in `packages/inter-protocol/src/proposals/econ-behaviors.js`. Is that expected?

2025-11-12 00:00 UTC, turadg commented on packages/SwingSet/src/controller/controller.js
> - * @import {default} from '../kernel/kernel.js';
to save time making line edits vs reverting on the CLI. this is a super lower priority project.

2025-11-12 01:26 UTC, merged