client support for Fast USDC
Agoric/Agoric pull request #10735
Opened 2024-12-18 19:33 UTC by turadg

closes: #10677

## Description

### Security Considerations

### Scaling Considerations

### Documentation Considerations

### Testing Considerations

### Upgrade Considerations

2025-01-24 23:30 UTC, dckc reviewed
oops... I think I misinterpreted a request-for-review notification

So these comments might be a bit premature...

2025-01-24 23:30 UTC, dckc commented on packages/fast-usdc/src/types.ts
> +export interface ContractRecord extends CopyRecord {
the name... does it refer to "the record you'll get from vstorage if you query the contract's node"?

docstring, please?

2025-01-24 23:30 UTC, dckc commented on packages/client-utils/src/types.d.ts
> +                ? Array<[string, Brand]>
A lot of the relevant code expects not just a `Brand` but a `Brand<'nat'>` or `Brand<'set'>`.

https://github.com/Agoric/agoric-sdk/blob/b2cb709533024613178948b2b291ce4b9b490932/multichain-testing/test/fast-usdc/fast-usdc.test.ts#L168
https://github.com/Agoric/agoric-sdk/blob/b2cb709533024613178948b2b291ce4b9b490932/multichain-testing/test/fast-usdc/fu-actors.ts#L39

I suppose one can add `as Brand<'nat'>`, but it almost defeats the point. It's also helpful to reassemble the entries into a record. Do you want to add helpers for this sort of thing?

2025-01-24 23:30 UTC, dckc commented on packages/client-utils/src/types.d.ts
> +                    ? PoolMetrics
It still feels strange for client-utils to depend on fast-usdc. Should it depend on dapp-offer-up and dapp-agoric-basics likewise?

It seems like fast-usdc should extend the type from client-utils.

2025-01-24 23:30 UTC, dckc commented on packages/fast-usdc/src/cli/lp-commands.js
> -      // @ts-expect-error it treats this as "unknown"
do you want to get rid of the type annotation while you're at it?

2025-01-24 23:30 UTC, dckc commented on packages/fast-usdc/src/exos/advancer.js
> -        settlementAddress: M.opt(ChainAddressShape),
good catch!

What prompted it, I wonder?

2025-01-25 00:08 UTC, turadg commented on packages/client-utils/src/types.d.ts
> +                ? Array<[string, Brand]>
agreed this is low value because you'll often want the kind of brand. It's still true tho so I think it's worth having here.

2025-01-25 00:09 UTC, turadg commented on packages/client-utils/src/types.d.ts
> +                    ? PoolMetrics
It is weird but ok for now. We'll have to solve it for https://github.com/Agoric/agoric-sdk/issues/10811

2025-01-25 00:09 UTC, turadg commented on packages/fast-usdc/src/cli/lp-commands.js
> -      // @ts-expect-error it treats this as "unknown"
oh yeah thanks

2025-01-25 00:09 UTC, turadg commented on packages/fast-usdc/src/exos/advancer.js
> -        settlementAddress: M.opt(ChainAddressShape),
I can't remember but I'm guessing some type feedback

2025-01-25 00:12 UTC, turadg commented
> these comments might be a bit premature...

Thanks they're helpful. I was just waiting for CI to get green before requesting.

In the interim I gave Aider with R1+Sonnet a spin. 88f0921798e3ef2e5ef8c7d3b4937acb2366395d has its solution to adding a ClientSupport module. LGTM! Minor cleanup in f4f6a52d05a16daac9ed764acaa1c2430ba685ec

2025-01-25 04:50 UTC, samsiegart approved these changes
From description:

> Everything in https://github.com/Agoric/agoric-sdk/issues/10677 except the offer makers. I think that'll come through Noble integration.

I think you added the offer makers in `packages/fast-usdc/src/clientSupport.js` right? Also, by Noble integration do you mean Noble Express UI? Because that won't be submitting any offers AFAIK. Only LPs and OCW will.

I'm assuming we're going to change the CLI and multichain-testing to use these offer functions in a later PR?

The actual code changes in this PR LGTM, so approving.

2025-01-25 04:50 UTC, samsiegart commented on packages/fast-usdc/src/clientSupport.js
Do we want to also add functions for accepting the operator invitation and submitting evidence?

2025-01-25 04:50 UTC, samsiegart commented on packages/fast-usdc/test/clientSupport.test.js
Test for `WithdrawFees`?

2025-01-25 04:50 UTC, samsiegart commented on packages/builders/scripts/fast-usdc/start-fast-usdc.build.js
> + * @import {FastUSDCConfig, FeedPolicy} from '@agoric/fast-usdc';
Nit: there's a semicolon here but not for the lines above. I wonder if eslint/prettier should have a rule for this

2025-01-25 05:44 UTC, dckc requested changes
Let's factor the offer makers out of existing code.

And as a result, let's leave `BoardRemote` behind and go from `Number` to ERTP ratio early.

2025-01-25 05:44 UTC, dckc commented on packages/fast-usdc/src/clientSupport.js
> +const makeDepositOffer = ({ brand }, instance, { offerId, amount }) => {
`want` is required, and the keyword is `USDC`, not `Deposit`.

I'd like us to re-use the existing fast usdc deposit type as in:

https://github.com/Agoric/agoric-sdk/blob/f0ccde6550d7f0d22fd489205cb12a6598faa2c9/packages/fast-usdc/src/cli/lp-commands.js#L104-L112

We could calculate the want for them if they pass in `metrics` or `shareWorth` as in...

https://github.com/Agoric/agoric-sdk/blob/f0ccde6550d7f0d22fd489205cb12a6598faa2c9/packages/fast-usdc/src/cli/lp-commands.js#L101-L102

We might want a `slippage` parameter.

2025-01-25 05:44 UTC, dckc commented on packages/fast-usdc/src/clientSupport.js
> + *   import('@agoric/vats/tools/board-utils.js').AgoricNamesRemotes,
Let's please stop using `BoardRemote` and hence `AgoricNamesRemotes`. Just use the ordinary types like `Brand`.

ref
 - #10491

2025-01-25 05:44 UTC, dckc commented on packages/fast-usdc/src/clientSupport.js
> +const scaleDecimals = num => BigInt(num * Number(COSMOS_UNIT));
Using `Number` has weird edge cases. For example, if the product inside `BigInt` isn't an integer, it throws.

Let's stick to ERTP `Amount` and `Ratio` as in:

https://github.com/Agoric/agoric-sdk/blob/f0ccde6550d7f0d22fd489205cb12a6598faa2c9/packages/fast-usdc/src/cli/lp-commands.js#L42-L46

`parseRatio` will take a `Number` or a `string` (anything that passes `assertParsableNumber`), so we could relax `amountString` likewise.

For commander-style arg parsing, we could export this one:

https://github.com/Agoric/agoric-sdk/blob/f0ccde6550d7f0d22fd489205cb12a6598faa2c9/packages/fast-usdc/src/cli/lp-commands.js#L28-L36

2025-01-25 05:44 UTC, dckc commented on packages/fast-usdc/src/clientSupport.js
> +        Deposit: {
```suggestion
        USDC: {
```

2025-01-25 05:44 UTC, dckc commented on packages/fast-usdc/src/clientSupport.js
> +const makeWithdrawOffer = ({ brand }, instance, { offerId, amount }) => ({
`give` is not optional when withdrawing.

again, let's factor this helper out of...

https://github.com/Agoric/agoric-sdk/blob/f0ccde6550d7f0d22fd489205cb12a6598faa2c9/packages/fast-usdc/src/cli/lp-commands.js#L134-L136

2025-01-25 05:44 UTC, dckc commented on packages/fast-usdc/src/clientSupport.js
> +export const Offers = {
Is there any particular reason to export this `Offers` structure rather than the functions `makeDepositOffer` and such?

2025-01-25 05:44 UTC, dckc commented on packages/fast-usdc/src/clientSupport.js
> +const makeWithdrawFeesOffer = (instance, { offerId }) => ({
This one is much less valuable; only a core-eval can withdraw fees.

But if we want to provide a helper, let's factor it out of...

https://github.com/Agoric/agoric-sdk/blob/f0ccde6550d7f0d22fd489205cb12a6598faa2c9/packages/fast-usdc/src/distribute-fees.core.js#L32

Note support for both absolute amounts and proportions.

2025-01-27 22:54 UTC, turadg commented on packages/builders/scripts/fast-usdc/start-fast-usdc.build.js
> + * @import {FastUSDCConfig, FeedPolicy} from '@agoric/fast-usdc';
I don't think ESlint has a linter for it. There's a Prettier plugin for JSDoc but it's quite buggy

2025-01-27 22:56 UTC, turadg commented on packages/fast-usdc/src/clientSupport.js
> +export const Offers = {
I don't have it handy but there was a PR for refactoring our tests to use these and it let you merge multiple of these into an `Offers` object with all the makers you needed.

2025-01-27 23:04 UTC, turadg commented on packages/fast-usdc/src/clientSupport.js
> + *   import('@agoric/vats/tools/board-utils.js').AgoricNamesRemotes,
I agree eventually but can you accept that as being out of scope? The `inter-protocol` clientSupport uses `AgoricNamesRemotes` and I think if we're going to change it we should do both.

2025-01-27 23:06 UTC, turadg commented on packages/fast-usdc/src/clientSupport.js
> +const scaleDecimals = num => BigInt(num * Number(COSMOS_UNIT));
One of the thing clientSupport helpers do is provide the brand. I think what you're asking for is a bigger change. Again I'm not fully opposed but I think it should be separated from this PR and cover the inter-protocol helper too.

2025-01-27 23:34 UTC, turadg commented on packages/fast-usdc/src/clientSupport.js
> +const scaleDecimals = num => BigInt(num * Number(COSMOS_UNIT));
I compromised by making it take a bigint but not the brand.

2025-01-28 00:00 UTC, dckc approved these changes
ok, this is forward progress.

2025-01-28 00:00 UTC, dckc commented on packages/fast-usdc/src/clientSupport.js
> + *   import('@agoric/vats/tools/board-utils.js').AgoricNamesRemotes,
> if we're going to change it we should do both.

I prefer the "platform is fixed" idea where fast-usdc is independent of inter-protocol. But I can live with this.

2025-01-28 00:00 UTC, dckc commented on packages/fast-usdc/src/clientSupport.js
> +    BecomeOperator: makeOperatorOffer,
I'd like to see a `WithdrawFees` offer maker factored our of `distribute-fees.core.js`. But I suppose it's reasonable to treat core eval stuff differently.

https://github.com/Agoric/agoric-sdk/pull/10735#discussion_r1929480733

2025-01-29 00:23 UTC, merged