refactor: Make it possible for keywords to be relative to an offer
Agoric/Agoric pull request #1093
Opened 2020-05-11 20:05 UTC by Chris-Hibbert

reduce reliance on instanceKeywordRecord in offer().
use a brandToIssuer table to find Issuers

This is the first step of facet parameters (#718).

2020-05-11 22:02 UTC, katelynsills requested changes
We shouldn't be passing in userKeywords to cleanProposal. that's causing us to perform a check that is essentially not checking anything. Instead, we should compare against the objective keywords until we've gone fully subjective, in which case, we need to check against what the contract provides for that offer, or something similar.

2020-05-11 22:02 UTC, katelynsills commented on packages/zoe/src/zoe.js
> +              const issuer = brandToIssuer.get(proposal.give[keyword].brand);
nice!

2020-05-12 00:31 UTC, Chris-Hibbert commented
> We shouldn't be passing in userKeywords to cleanProposal. that's causing us to perform a check that is essentially not checking anything.
Yeah, you're right that these changes don't stand on their own. 

I now commit that this won't get merged except as a branch with a complete refactoring for the whole Facet Parameters change. Do you want to review it a little at a time, or wait for it to be a coherent whole?

I'll look at the rest of your comments now, and fold in the ones that aren't just pointing out that this change isn't complete on its own.

2020-05-12 00:37 UTC, katelynsills commented
> I now commit that this won't get merged except as a branch with a complete refactoring for the whole Facet Parameters change. Do you want to review it a little at a time, or wait for it to be a coherent whole?
> 
> I'll look at the rest of your comments now, and fold in the ones that aren't just pointing out that this change isn't complete on its own.

Ok, that sounds good. I'm ok waiting for the coherent whole.

2020-05-12 01:46 UTC, erights commented
I prefer to wait for the coherent whole as well. Thanks.

2020-06-18 16:46 UTC, Chris-Hibbert commented
The relevant parts of this have been merged into the Zoe 0.7.0 branch #1143.

2020-06-18 16:46 UTC, closed without merging