Adding some comments documenting captp.js.
Agoric/Agoric pull request #1139
Opened 2020-05-27 19:32 UTC by cwebber

First pass: there are some unanswered questions in the comments and some things are probably wrong!

I'd love review about how much I understand this... and I figured, while I'm trying to figure it out, maybe my attempt-at-understanding is generally useful for the module.

There are some questions (marked with `???`) amongst the comments and some things are probably flat-out wrong, so review is encouraged before merging.

I'm happy to make some changes if you are willing to review... or if you'd prefer to just modify and pull in yourself, that's welcome too.

2020-05-27 19:42 UTC, cwebber commented
Also I don't know anything about Agoric's style guide (or contemporary Javascript style at all) so sorry for the failing linting tests :)

2020-05-27 21:55 UTC, cwebber commented
BTW, an additional thing to possibly comment, once understood:

```
<Zarutian_HTC> dustyweb: one thing I noticed about CTP_RETURN that the question gets deleted. No idea why.
<Zarutian_HTC> seem to prevent usage patterns like: const t1 = remoteObj~.x(); t1.y(); t1.z();
<dustyweb> Zarutian_HTC: yes that is curious
<dustyweb> Zarutian_HTC: mind if I put that on the issue tracker?
<Zarutian_HTC> sure
<dustyweb> Zarutian_HTC: I have a guess
<dustyweb> it's an attempt to prevent things from getting too out of hand before GC support in captp
<dustyweb> .js
<Zarutian_HTC> right
<Zarutian_HTC> the gc thing requires weakref and post mortem finalization
```

Are we right? :)

2020-05-27 23:42 UTC, michaelfig commented
> Are we right? :)

Probably! :)

BTW, your comments are welcome.  You can look at the current CapTP as me trying to read and understand the Cap'n'Proto implementation and the liveSlots.js implementation, but not as well-documented.

2020-06-12 16:29 UTC, michaelfig requested changes
Just a few changes.  Thanks for this!

2020-06-12 16:29 UTC, michaelfig commented on packages/captp/lib/captp.js
> +  const valToSlot = new WeakMap();   // exports looked up by val
These lint complaints are due to prettier only allowing a single space between the end of line and `//`.  Could you please fix this?

2020-06-12 16:29 UTC, michaelfig commented on packages/captp/lib/captp.js
> +    // (??? cwebber): Why is this inverted this way?  In what circumstance
The direction prevents namespace collisions between the slots we allocate and the ones that the other side allocates.  If we allocate a slot, serialise it to the other side, and they send it back to us, we need to reference just our own slot, not one from their side.

2020-06-12 16:29 UTC, michaelfig commented on packages/captp/lib/captp.js
> +      // (??? cwebber): Not sure that's well phrased or even if I understand
Yup, you understand it at least as well as it was written.

2020-06-16 20:51 UTC, cwebber commented
Updated.  Thank you!

(I don't completely understand *why* the directionality is introduced however... my read on the imports/exports and questions/answers per reading the original captp documentation is that the imports/exports end up being "specified" by the exporter and that questions/answers are "specified" by the questioner, and this is relevant to the way that collaborative GC ends up happening.  But maybe I've misunderstood something... anyway, not critical to getting this PR in.)

2020-06-18 16:47 UTC, michaelfig approved these changes

2020-06-18 16:48 UTC, merged