refactor: IssuerTable based on brands rather than Keywords
Agoric/Agoric pull request #1168
Opened 2020-06-09 21:28 UTC by Chris-Hibbert

Extracted from Zoe facet parameters (in progress)

2020-06-09 22:32 UTC, katelynsills requested changes
I think the core of this looks very good. There are some extraneous things and one addition to the API that I want to remove, but otherwise looks ready to merge

2020-06-09 22:32 UTC, katelynsills commented on packages/zoe/src/zoe.js
> +    return amountMathKeywordRecord;
should we keep the harden?

2020-06-09 22:32 UTC, katelynsills commented on packages/zoe/src/state.js
> +    function buildTableEntryAndPlaceHolder(issuer) {
Pulling this out into a separate function is a great idea

2020-06-09 23:58 UTC, Chris-Hibbert commented on packages/zoe/src/zoe.js
> +      getAmountMathForBrand,
done

2020-06-09 23:58 UTC, Chris-Hibbert commented on packages/zoe/src/zoe.js
> +    return amountMathKeywordRecord;
done

2020-06-09 23:58 UTC, Chris-Hibbert commented on package.json
> +    "@agoric/store": "^0.1.2"
done

2020-06-09 23:59 UTC, Chris-Hibbert commented
Sorry, just saw some more comments. I'll address them now.

2020-06-10 00:24 UTC, katelynsills approved these changes
Looks good! Thanks!

2020-06-10 16:08 UTC, merged