feat: add getIssuerFromBrand to zoe
Agoric/Agoric pull request #1276
Opened 2020-07-09 06:06 UTC by dtribble

closes: #1270

2020-07-09 17:59 UTC, katelynsills commented
This looks good. Before merging can we add a unit test and coordinate with @tyg to change the documentation?

2020-07-13 21:47 UTC, katelynsills requested changes
I think there are some linting errors and we might need to rebase this on master for only the wanted changes to show. Can we also add unit tests for this and coordinate with Tom on updating the documentation?

2020-07-17 23:11 UTC, katelynsills commented
Added a test, @dtribble do you want to take a look at it? I also asked Chris to review

2020-07-18 01:01 UTC, katelynsills approved these changes

2020-07-19 20:43 UTC, Chris-Hibbert requested changes
These look like useful helpers. I'm skeptical about adding a helper for the tests and not invoking it anywhere.

2020-07-19 20:43 UTC, Chris-Hibbert commented on packages/zoe/test/unitTests/contracts/zcfTesterContract.js
> +export { makeContract };
Is this intended to be called? Is it a replacement for current functionality in the tests?

2020-07-20 18:25 UTC, katelynsills commented
> These look like useful helpers. I'm skeptical about adding a helper for the tests and not invoking it anywhere.

I'm not sure what you mean. `zcfTesterContract.js` is run as the main part of this test, so everything added is invoked

2020-07-20 19:03 UTC, Chris-Hibbert commented
> `zcfTesterContract.js` is run as the main part of this test, so everything added is invoked

Thanks, I was looking for `makeContract` and missed that  the file was imported explicitly.

2020-07-20 19:03 UTC, Chris-Hibbert approved these changes

2020-07-20 19:04 UTC, merged