refactor: fix liquidity bug in autoswap, add doc, better tests
Agoric/Agoric pull request #1586
Opened 2020-08-22 01:14 UTC by Chris-Hibbert

Fixed a bug in add liquidity that wasn't enforcing proportionality

built a test jig for autoswap
Change liquidity keywords to match multipoolAutoswap
don't allow swap before pools are initialized
Added calculation of price for a stated quantity of output
Treated a trade with a specified quantity of output as a request for exactly that much
improve documentation

addresses #1600 , but doesn't fix it, since the same issue also applies to multipoolAutoswap

2020-08-24 22:11 UTC, katelynsills requested changes
I like the jig a lot! I think the jig can be simplified by only mentioning central and secondary and abstracting over what actual token they are. Also, I think we should not use the `Out` of a swap as a statement of wanting exactly that much. We need it for offer safety, so we should instead have two swap endpoints.

2020-08-24 22:11 UTC, katelynsills commented on packages/zoe/test/unitTests/contracts/test-autoswap.js
> +      t.equals(kPost, sPost * mPost, 'expected value of K after addLiquidity');
hmm, isn't the constant product such that we shouldn't have a `kPost` variable? Constant product would mean that we could use `kPre` and assert that `sPost * mPost` >= than `kPre`.

2020-08-24 22:11 UTC, katelynsills commented on packages/zoe/test/unitTests/contracts/test-autoswap.js
> +      t.assert(lPost >= lAmount, 'liquidity want was honored');
can we use amounts rather than values?

2020-08-24 22:11 UTC, katelynsills commented on packages/zoe/test/unitTests/contracts/test-autoswap.js
> +    t.assert(t, '..Alice added liquidity');
huh, what does this do?

2020-08-24 22:11 UTC, katelynsills commented on packages/zoe/test/unitTests/contracts/test-autoswap.js
> +    await alice.initLiquidityAndCheck(
nice!!

2020-08-24 22:11 UTC, katelynsills commented on packages/zoe/test/unitTests/contracts/test-autoswap.js
> +      k: 11000 * 9094,
I think we shouldn't be calculating postK, but rather using >= preK as the invariant

2020-08-24 22:11 UTC, katelynsills commented on packages/zoe/test/unitTests/contracts/test-autoswap.js
> +      k: 11000 * 9094,
Seems like we are not testing as much if we hard-code postK based on the swap output that we get from our own code.

2020-08-24 22:11 UTC, katelynsills commented on packages/zoe/test/unitTests/contracts/test-autoswap.js
> +    const liqExpected1 = scaleForAdd(poolState, { m: 1100, s: 910 }, true);
huh, should we make this part of the addLiquidityAndCheck function?

2020-08-24 22:11 UTC, katelynsills commented on packages/zoe/test/unitTests/contracts/test-autoswap.js
> +      .then(async () =>
hmm, if seat.getOfferResult() rejects, how does this get called, when it's the resolves callback?

2020-08-25 00:54 UTC, Chris-Hibbert reviewed
I've responded to most of your questions, but haven't finished making changes to the code.

2020-08-25 00:54 UTC, Chris-Hibbert commented on packages/zoe/src/contractSupport/bondingCurves.js
> +  // exactly equal, lPrime is exactly l * (1 + alpha) and adding one is wrong
The paper says "The invariant is that the ratio of `e:t:l` is preserved" in section 2.1.1, but there's no code in 2.1.2 that enforces it. The code that handles that in the Uniswap contract is the `assert`.

```
liquidity_minted: uint256 = msg.value * total_liquidity / eth_reserve
assert max_tokens >= token_amount and liquidity_minted >= min_liquidity
```

> Hmm, I find this very confusing. First, this should be the same calculation as calcLiqValueToMint, right, at least according to the paper? So let's not create a new function.

It's not the same. In section 2.1.1, they're isomorphic, but in 2.1.2, they're different. If we do the same as the paper, we have to add 1.  When the ratio of `e:t:l` is exactly `e":t":l"` there's no reason to add 1 other than compatibility with the paper.  Adding 1 makes an unnecessary change to K.

> On the other hand, the uniswap v1 code explicitly adds 1 no matter what. I don't know why.

It's easier. They might have not noticed that if the ratio's right, you don't have to add 1 to maintain the invariants.

> Also, this code seems to be different than both of them, but I don't understand why.


If you ignore the computation of `exact`, they're doing the same arithmetic:

addLiquidity calls 
``` js
calcLiqValueToMint(
      harden({ liqTokenSupply, inputValue: centralIn, inputReserve: centralPool }));
```
and calcLiqValueToMint does this
``` js
 floorDivide(multiply(inputValue, liqTokenSupply), inputReserve);
```
while `addLiquidityHandler` calls 
```js
calcSecondaryRequired({ centralIn, centralPool, secondaryPool, secondaryIn });
```
and `calcSecondaryRequired` does
``` js
floorDivide(multiply(centralIn, secondaryPool), centralPool);
```
so they're multiplying `centralIn/centralPool` by either the secondary token coming in or the liquidity before the operation. These give the values in the `floor` brackets in section 2.1.2.

2020-08-25 00:54 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> + * specified in the terms.issuers. There is no behavioral difference between the
thanks. I changed ti to refer to the keywordRecord.

2020-08-25 00:54 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> + * it's positive, it is treated as a request for an exact amount of output, and
I agree that that's a better choice.

2020-08-25 00:54 UTC, Chris-Hibbert commented on packages/zoe/test/unitTests/contracts/test-autoswap.js
> +      t.assert(payoutM === 0 || payoutS === 0, 'only refund one side');
Ooh, good point. I don't think I'm checking that they didn't ask for too much liquidity. That would only have failed in offer safety or conservation. I'll add a test case.

2020-08-25 20:57 UTC, katelynsills commented on packages/zoe/src/contracts/autoswap.js
> + * specified in the terms.issuers. There is no behavioral difference between the
Sounds good!

2020-08-25 21:03 UTC, katelynsills commented on packages/zoe/test/unitTests/contracts/test-autoswap.js
> +      t.equals(kPost, sPost * mPost, 'expected value of K after addLiquidity');
Ah, gotcha. I forgot that it only applies to swaps. Adding or removing liquidity would affect k considerably. Looks good tome!

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +   * specifies the wanted asset. If the want amount is 0, all of the In amount
sounds good.

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    if (secondaryIn < secondaryOut) {
okay

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    return addLiquidity(liqSeat, centralIn, centralPool, secondaryOut);
The seat and the amount of secondary to trade.

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    if (centralPool === 0) {
good idea.

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    getPriceForOutput,
getInputPrice and getOutputPrice.

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    getLiquidityTokens: () => liqTokenSupply,
getLiquiditySupply.

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/test/swingsetTests/zoe/vat-bob.js
> +      // Bob looks up the price of 6 moola. It's 3 simoleans
sure, that's clearer

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/test/swingsetTests/zoe/vat-bob.js
> +        want: { Out: simoleans(0) },
Now that we're distinguishing swapIn from swapOut, Bob can go back to specifying his want.

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    const userAllocation = liqSeat.getCurrentAllocation();
done.  The way I was doing things previously, the check depended on this value.

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +      if (tradePrice > amountIn.value) {
done

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    if (wantedAmountOut.value > 0) {
done

2020-08-26 00:51 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    if (getPoolAmount(brands.Central).value === 0) {
done

2020-08-26 21:01 UTC, katelynsills requested changes
This is looking good! I think there is still a problem with how we are treating the `want` of 0 as a special case in SwapIn and SwapOut.

2020-08-26 21:01 UTC, katelynsills commented on packages/zoe/test/unitTests/contracts/test-autoswap.js
> +      .then(async () =>
This needs to be awaited, or otherwise gathered up

2020-08-26 22:12 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +   * @type {OfferHandler}
The documentation lags behind the code. You are correct.

2020-08-26 22:13 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +   *
You are correct. I fixed the top comment, but missed this one.

2020-08-26 22:14 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    const tradeAmountIn = amountIn;
agreed.

2020-08-26 22:14 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    const tradeAmountOut = wantedAmountOut;
yep.

2020-08-26 22:33 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    assert(tradePrice <= amountIn.value, 'amountIn insufficient');
done.

2020-08-26 22:33 UTC, Chris-Hibbert commented on packages/zoe/src/contracts/autoswap.js
> +    assert(secondaryIn >= secondaryOut, 'insufficient Secondary deposited');
done

2020-08-27 20:13 UTC, katelynsills approved these changes
LGTM!

2020-08-27 20:16 UTC, merged