Convert ERTP to Ava
Agoric/Agoric pull request #1587
Opened 2020-08-22 01:24 UTC by dtribble

refs #1568

2020-08-22 01:46 UTC, warner requested changes
there's a bogus `packages/er.tar` in the commit, as well as `packages/old/`

also bogus generated files like `testdb-lmdb/data.mdb`, `testdb/swingset-kernel-state.jsonlines`

these all need to be removed

Once those are removed (and squashed, so the final history doesn't add+remove them), and CI fixed, and the top-level unused `ava.config.js` is removed, I think this is good to land.

2020-08-22 02:37 UTC, katelynsills requested changes
I concur with Brian. There are some additional files that should be removed, but most of the test changes look good. There are some uses of mathHelpers that seem to be an accident, where the original was correct.

2020-08-24 17:52 UTC, dtribble commented on packages/ERTP/package.json
> +      "@agoric/install-ses",
Yes that fixed it. I'll fold this into the package.json.

2020-08-24 17:53 UTC, dtribble commented on ava.config.js
> +export default {
OK it looks like all the files laying around got dragged into the branch. I'll get rid of them

2020-08-24 18:27 UTC, dtribble commented on packages/ERTP/test/unitTests/test-issuerObj.js
> +  return E(issuer)
I agree. Moving to `await` here seems like the right thing

2020-08-24 18:29 UTC, dtribble commented on packages/ERTP/test/unitTests/test-issuerObj.js
>      .then(checkDeposit)
I think I agree with the earlier conversation that using `await` at the end is better for overall consistency.

2020-08-24 22:52 UTC, dtribble commented on packages/ERTP/test/unitTests/test-issuerObj.js
> +test('issuer.getAmountMath', async t => {
definitely bad merge. The change to MathKinds came after I forked for the ava spike, and the merge of those changes wasn't right.

2020-08-26 00:08 UTC, closed without merging