fix: return better error messages in the case of a bad issuer
Agoric/Agoric pull request #1793
Opened 2020-09-17 00:30 UTC by katelynsills

Closes #1701
Closes #1702

2020-09-17 17:01 UTC, Chris-Hibbert commented on packages/zoe/src/issuerTable.js
> +        ([issuer, brand, brandIssuerMatch, amountMathKind] = await Promise.all([
This type declaration isn't actually having the effect it should. If you hover over any of the variables in the next line, they show as `any`.  I'd try putting the type declarations on the variable declarations (lines 43-46)

2020-09-17 17:44 UTC, Chris-Hibbert approved these changes
This seems fine.  I added some comments that may point a direction to fixing the lint problem.  It may  be worth adding error messages on the bare asserts. Otherwise, approved.

2020-09-17 17:44 UTC, Chris-Hibbert commented on packages/zoe/src/issuerTable.js
> +      assert(amountMathKind);
should these have error messages?

2020-09-17 20:31 UTC, erights requested changes

2020-09-17 20:31 UTC, erights commented on packages/zoe/src/issuerTable.js
> +        ([issuer, brand, brandIssuerMatch, amountMathKind] = await Promise.all([
`await` inside a `try` violates our rules. It is silly in this case anyway. Please rephrase your catch clause as a rejection handler on the promise returned by `Promise.all`.

2020-09-17 20:31 UTC, erights commented on packages/zoe/src/issuerTable.js
> +        assert.fail(
Please add a TODO here to rethrow the error after adding the details as a note (for upcoming assert library). The problem, which you can't fix well until then, is that the error you're throwing no longer has the informative stack trace of the error you caught.

2020-09-17 20:44 UTC, katelynsills commented
@erights it is this PR in particular that will benefit from `getInterfaceOf`.

2020-09-30 21:09 UTC, katelynsills commented
Closing this in favor of a new PR when we can get `getInterfaceOf` in a different way than `vatPowers.getInterfaceOf`. See #1816

2020-09-30 21:09 UTC, closed without merging