chore: provide GC tools (WeakRef/FinalizationRegistry) to makeLiveSlots
Agoric/Agoric pull request #1924
Opened 2020-10-26 16:39 UTC by warner

These two authorities are not part of SES, so they must be pulled from the
globals of the Start Compartment and ferried through the kernel to the vat
manager factory that calls makeLiveSlots.

This gives the outer layer of the vat (liveslots) access to nondeterminism.
We rely upon liveslots to not share this power with the user-level ocap-style
"vat code". Liveslots must never allow user-level code to observe behavior
that depends upon GC activity, because that activity is not part of the
specified input to the vat.

These tools are not used by liveslots yet, that will come in a later PR.

refs #1872

2020-10-26 16:53 UTC, warner commented
Hm, it looks like the test failures are because Node 12.x does not expose `WeakRef` by default, but Node 14.x does. This might prompt us to increase our required Node.js version to 14, rather than instruct users to add whatever command-line option might enable weakrefs in 12 (if there even is such a thing.. I see `--harmony-weak-refs`, but it's labelled as "in progress").

2020-10-26 18:27 UTC, warner commented
Based on our discussion, we're going to provide backwards compatibility with Node v12, which means the liveslots code will either get the real `WeakRef`, or it will create a strong-reference-holding stub.

2020-10-26 19:32 UTC, warner commented
I'm going to change this to provide a no-op implementation under Node v12, I'll re-submit for review once that's done.

2020-10-26 20:52 UTC, warner commented
@erights am I taming the generated stub object correctly? I don't know that I'm deleting the right `.constructor` property.

2020-10-27 02:04 UTC, FUDCo approved these changes
Looks fine, though I think we're going to want to do something about the proliferation of parameters to `makeLiveSlots`

2020-10-27 03:34 UTC, erights requested changes
DO NOT MERGE THIS IN ITS CURRENT STATE. My review coming soon.

2020-10-27 04:38 UTC, erights requested changes
Aside from my suggestions at #1931 , this LGTM

2020-10-27 09:11 UTC, erights approved these changes
LGTM

2020-10-27 17:02 UTC, merged