Fix filtered offers notifier
Agoric/Agoric pull request #2184
Opened 2021-01-11 23:44 UTC by dtribble

fix: dapp offersNotifiers should use dapp-local keys

Remove the dappOrigin# from the offer IDs in the
`getOffersNotifier` so that the ID can be used to request
the `getUiNotifier` and other offer services.

2021-01-11 23:50 UTC, michaelfig requested changes
Needs a little fix to prevent accidental errors.

2021-01-11 23:50 UTC, michaelfig commented on packages/dapp-svelte-wallet/api/src/wallet.js
> +            id: id.slice(dappOrigin.length + 1),
I'd like to make this more robust.  Will push a change.

2021-01-11 23:50 UTC, katelynsills commented on packages/dapp-svelte-wallet/api/src/wallet.js
> +            id: id.slice(dappOrigin.length + 1),
Can we instead store `rawId` in `lib-wallet.js` line 812 and use that here instead rather than breaking up `id`?

2021-01-12 00:40 UTC, katelynsills approved these changes
LGTM!

2021-01-12 00:53 UTC, merged