add support for E.get()
Agoric/Agoric pull request #2616
Opened 2021-03-10 22:15 UTC by Chris-Hibbert

related: #2502

@michaelfig  Is there a good way to mark `E.G()` as deprecated?

2021-03-10 22:49 UTC, michaelfig requested changes
Would you also consider adding a global search-and-replace for `\bE\.G\b` to `E.get`?

That way it's only dapps and external users who might possibly have (deprecated) references to `E.G`.

2021-03-10 22:49 UTC, michaelfig commented on packages/eventual-send/src/index.d.ts
You may be able to mark the above with `@deprecated`.

2021-03-18 06:37 UTC, michaelfig commented on packages/eventual-send/src/index.d.ts
I did that, but it doesn't seem to change anything.  Unfortunate.

2021-03-18 06:40 UTC, michaelfig approved these changes
LGTM, but I don't want to approve my own changes.  @Chris-Hibbert, @erights can you have a quick peek?

2021-03-18 06:48 UTC, michaelfig commented
> Would you also consider adding a global search-and-replace for `\bE\.G\b` to `E.get`?

I actually used `\bE\.G\b(\(|;)` to `E.get$1`.  Seemed to work well.

2021-03-18 16:11 UTC, Chris-Hibbert reviewed
Looks great!  I couldn't find any missed instances locally.  Thanks very much.

2021-03-18 16:12 UTC, merged