Convert APR to appropriate rate for fine-grain compounding
Agoric/Agoric pull request #2834
Opened 2021-04-07 05:21 UTC by Chris-Hibbert

Had to rejigger a bunch of tests, using longer timeframes and larger
    borrowed amounts
Made manualTimer and scriptedPriceAuthority understand a timestep so
   we could do things by large fractions of a year

2021-04-08 01:12 UTC, Chris-Hibbert commented
@dtribble, I think you asked for a guide to how to think about the numbers in the various tests, though I haven't been able to locate that conversation.

* `vault-contract-wrapper` needed to have larger time steps. This affects `test-vault` and`test-vault-interest`. I think I would get rid of both as the functionality they test is better covered elsewhere. They're a hassle to maintain.
* `test-vault-interest` needed loan and collateral multiplied by 100 or so or no interest would have been charged.
* in `test-stablecoin`, I changed the charging- and recording-periods for the tests that paid attention to interest to a week to make sense of the annual rate, and changed the manualTimer to move a day at a time. I'd have to boost the loan amounts for interest at 5%APR to be non-negligible when charged daily or weekly.  As it is, they're being charged single digit amounts of interest per day or week.
* In `test-interest`, daily interest on a loan of 100000n at 2.5% APR is 6n. These tests verify that the correct number of days of interest are charged as the calculate takes different parameters. There's at least one test case that makes the charging period be a month, and I verified that 203n, is the right charge for that.

2021-04-11 18:50 UTC, dtribble requested changes
Mostly comment changes, but they are important for maintenance.

2021-04-11 18:50 UTC, dtribble commented on packages/treasury/test/test-interest.js
> +  const annualRate = makeRatio(250, brand, 10000n);
use BASIS_POINTS constants

2021-04-11 18:50 UTC, dtribble commented on packages/treasury/test/test-interest.js
> +    interest: amountMath.make(6n, brand),
Comment: 
6n is daily interest of 2.5% APR on 100k. The compounded interest is lost in the noise.

2021-04-11 18:50 UTC, dtribble commented on packages/treasury/test/test-interest.js
>    const debtStatus = {
comment: test interest between the 1st day and the 3rd day, which should be 6 (daily interest) * 2

2021-04-11 18:50 UTC, dtribble commented on packages/treasury/test/test-interest.js
> +    interest: amountMath.make(0n, brand),
`amountMath.makeEmpy(brand)`?

2021-04-11 18:50 UTC, dtribble commented on packages/treasury/test/test-interest.js
>    const START_TIME = 1617734746n;
Comment: This is a UNIX epoch time. 
Please say what the time is supposed to be.

2021-04-11 18:50 UTC, dtribble commented on packages/treasury/test/test-interest.js
>    const START_TIME = 1617734746n;
Tuesday April 6th 2021 at 11:45am PT

2021-04-11 18:50 UTC, dtribble commented on packages/treasury/test/test-interest.js
> +    interest: amountMath.make(676n, brand),
make this a magic constant?  676 is the daily * 100 with the compounding

2021-04-11 18:50 UTC, dtribble commented on packages/treasury/test/test-interest.js
>    // Notice that interest is compounding: 30 * 684 = 20520
update comment for 676

2021-04-11 18:50 UTC, dtribble commented on packages/treasury/test/test-interest.js
>  // 2.5 % APR charged weekly, charged monthly
fix comment

2021-04-11 18:50 UTC, dtribble commented on packages/treasury/test/test-interest.js
> +    interest: amountMath.make(0n, brand),
`makeEmpty`

2021-04-11 18:50 UTC, dtribble commented on packages/treasury/test/test-stablecoin.js
> +  const bobAddedDebt = 160n + 3n;
comment: initial fee + 1/day (compounding is in the noise)

2021-04-13 00:57 UTC, dtribble approved these changes
I have 2 constant naming thoughts, but they aren't blocking

2021-04-13 00:57 UTC, dtribble commented on packages/treasury/test/test-interest.js
> +const HUNDRED_THOUSAND = 100000n;
BASIS_POINTS makes sense. The mere numeric ones are not clarifying as to their purpose. TEST_SCALE to make sure we have significant digits?

2021-04-13 00:57 UTC, dtribble commented on packages/treasury/test/test-interest.js
> +const HUNDRED_THOUSAND = 100000n;
Ah. I see below that TEN_MILLION is "LARGE_DEBT"? Perhaps HUNDRED_THOUSAND is MEDIUM_DEBT?

2021-04-13 05:01 UTC, merged