Add a Swingset test for the Treasury
Agoric/Agoric pull request #2890
Opened 2021-04-15 22:53 UTC by Chris-Hibbert

add a Swingset test for the Treasury

update some type declarations and use `E()` where necessary.

2021-04-19 23:52 UTC, dtribble commented on packages/treasury/test/swingsetTests/vat-owner.js
> +      priceList: [100000n, 120000n, 110000n, 80000n],
does this need hardening since it is in a different vat?

2021-04-20 00:08 UTC, dtribble requested changes
Some `await` fixes, but otherwise it's great

2021-04-20 00:08 UTC, dtribble commented on packages/treasury/test/swingsetTests/test-treasury.js
> +    bundle: await bundleSource(bootstrapSource),
can this be in the previous Promise.all?  Also, this `await` needs to move to the top level.

2021-04-20 00:08 UTC, dtribble commented on packages/treasury/test/swingsetTests/test-treasury.js
> +  const controller = await buildVatController(config, argv, { kernelBundles });
Why do we await this, rather than queuing up the `run` operation?

2021-04-20 23:38 UTC, Chris-Hibbert commented on packages/treasury/test/swingsetTests/bootstrap.js
> +        liquidateMinimum: await E(zoe).install(cb.liquidateMinimum),
I pulled it out. Is the new location (line 63) top-level enough?

2021-04-21 16:08 UTC, dtribble approved these changes

2021-04-21 16:24 UTC, merged