refactor: get ERTP into a better form for auditing
Agoric/Agoric pull request #3117
Opened 2021-05-18 00:31 UTC by katelynsills

This PR is a refactoring of ERTP in order to make it easier to audit. 

Included refactorings:
* The tests/ directory was added to `jsconfig.json` so tests are now type checked.
* All tests and code in ERTP uses the "brand-first" `AmountMath.make`, `AmountMath.coerce`, and `AmountMath.getValue`. The methods still support the deprecated order, however.
* The `paymentLedger` has been pulled into its own file and the capability to add a new payment entry is entirely encapsulated in the `mint` and `issuer` methods. 
* `brand` and `purse` have been pulled out into separate files for easier reasoning about their access and risk.
* `makeExternalStore` is no longer used.
* The calling of `Far` with a particular allegedName has been cleaned up in a way that still allows for easy testing and no magic strings.

Closes #3046

2021-05-19 05:04 UTC, erights approved these changes
Just review so far. I have reviewed everything except the paymentLedger itself, which is of course central.

I was surprised to see that paymentLedger actually creates the issuer object. But now that the issuer object is mostly a set of methods for operating on payments, that makes sense.

Everything looking good to me so far. All issues minor.

2021-05-19 21:41 UTC, katelynsills commented on packages/ERTP/src/markObjects.js
> +export const ERTPKind = {
It's only motivated by not having to have magical strings in testing

2021-05-19 21:45 UTC, katelynsills commented on packages/ERTP/test/unitTests/mathHelpers/mockBrand.js
> +  isMyIssuer: async allegedIssuer => false && allegedIssuer,
This is just to use the `allegedIssuer` so that ESLint doesn't complain about the mockBrand not having the same API as a real brand.

2021-05-19 21:51 UTC, katelynsills commented on packages/ERTP/src/markObjects.js
> +export const ERTPKind = {
Oh, actually that test got removed. Yup, I'll remove all of this.

2021-05-19 22:01 UTC, katelynsills commented on packages/ERTP/src/markObjects.js
> +export const ERTPKind = {
Removed

2021-05-19 22:02 UTC, katelynsills commented on packages/ERTP/src/markObjects.js
> +  Far(makeFarName(allegedName, ERTPKind.BRAND), brand);
Just took this out entirely.

2021-05-19 22:03 UTC, katelynsills commented on packages/ERTP/src/markObjects.js
> +export const makeFarName = (allegedName, kind) => `${allegedName} ${kind}`;
Done!

2021-05-19 22:06 UTC, katelynsills commented on packages/ERTP/test/unitTests/mathHelpers/mockBrand.js
> +  isMyIssuer: async allegedIssuer => false && allegedIssuer,
Added an eslint ignore instead

2021-05-19 22:06 UTC, katelynsills commented on packages/ERTP/src/purse.js
> +    },
Done

2021-05-20 23:02 UTC, erights requested changes
Just some questions and minor improvements requested.

2021-05-21 01:19 UTC, katelynsills commented on packages/ERTP/src/paymentLedger.js
> +/* global makeWeakStore */
To sum up: this PR was made 3 days ago, the PR that made `===` work for virtual objects was merged 2 days ago, and I learned that that particular PR made`===` work for virtual objects today. :D 

So, I think the plan is, I can amend this PR to use the native `Set` for anti-aliasing, and to use the `@agoric/store` `makeWeakStore`. @FUDCo says both should work now.

2021-05-21 01:20 UTC, katelynsills commented on packages/ERTP/src/paymentLedger.js
> +      const antiAliasingStore = makeWeakStore('payment');
We should be able to use a native `Set` now, I believe, but that has been enabled since this PR was made. I will change the PR to use a Set.

2021-05-21 01:32 UTC, katelynsills commented on packages/ERTP/src/payment.js
>        init: b => (state.brand = b),
Thanks!

2021-05-21 01:33 UTC, katelynsills commented on packages/ERTP/src/paymentLedger.js
> +    commit(newPurseBalance);
Sure, I think `updatePurseBalance` would be fine

2021-05-21 01:39 UTC, katelynsills commented on packages/ERTP/src/paymentLedger.js
> +  const assertAmountEqual = (paymentBalance, amount) => {
Ok, that sounds good to me.

2021-05-21 01:58 UTC, erights commented
Note to @katelynsills : Although https://github.com/endojs/endo/pull/733 and https://github.com/Agoric/agoric-sdk/pull/3144 were stimulated by https://github.com/Agoric/agoric-sdk/pull/3117 , there is no need to look at them in order to proceed with https://github.com/Agoric/agoric-sdk/pull/3117 or anything else urgent. But once more urgent matters are behind us, it would be good to get this extra safety check threaded through our system.

2021-05-21 01:58 UTC, katelynsills commented on packages/ERTP/src/paymentLedger.js
> +    // Note: this does not guarantee that optAmount itself is a valid stable amount
I believe I added that comment at your direction, to make sure we didn't use the user-provided `optAmount` later in the uncoerced form:

https://github.com/Agoric/agoric-sdk/pull/523/files#r382361674

The link wasn't reliably getting to the comment for me, so here's a screenshot too:

<img width="970" alt="Screen Shot 2021-05-20 at 6 55 52 PM" src="https://user-images.githubusercontent.com/2441069/119070597-2b285680-b99d-11eb-90f3-bd4f5481402d.png">

What do you think? Should we change the comment? Remove it?

2021-05-21 01:59 UTC, katelynsills commented on packages/ERTP/src/paymentLedger.js
> +/* global makeWeakStore */
Switched to `Set` and `@agoric/store makeWeakStore`

2021-05-21 01:59 UTC, katelynsills commented on packages/ERTP/src/paymentLedger.js
> +    assert(isEqual(total, newTotal), 'rights were not conserved');
Done!

2021-05-21 02:00 UTC, katelynsills commented on packages/ERTP/src/paymentLedger.js
> +      assertKnownPayment(payment);
That sounds right to me. Done

2021-05-21 02:00 UTC, katelynsills commented on packages/ERTP/src/paymentLedger.js
> +        `deposit does not accept promises as first argument. Instead of passing the promise (deposit(paymentPromise)), consider unwrapping the promise first: paymentPromise.then(actualPayment => depo
Done

2021-05-21 02:00 UTC, katelynsills commented on packages/ERTP/src/paymentLedger.js
> +    commit(newPurseBalance);
Done

2021-05-21 02:03 UTC, erights commented on packages/ERTP/src/paymentLedger.js
> +    // Note: this does not guarantee that optAmount itself is a valid stable amount
Keep the comment. I underestimated it now and will have to think more about my earlier worries. Thanks for the reminder!

I may suggest a rewording but don't worry about that now. Certainly, this PR need not wait on such a rewording.

2021-05-21 02:04 UTC, erights commented on packages/ERTP/src/paymentLedger.js
> +    // Note: this does not guarantee that optAmount itself is a valid stable amount
No change suggested. Resolving.

2021-05-21 02:05 UTC, erights approved these changes
LGTM!

2021-05-21 21:09 UTC, merged