fix(xsnap): tame XS deep freeze in SES workers
Agoric/Agoric pull request #3603
Opened 2021-08-04 22:32 UTC by dckc

This adds an extra function call for every `Object.freeze()` call. I'm not sure we want that, given @phoddie 's offer to make deep-freeze a compile-time opt-out feature.

Meanwhile, testing that this feature is not available to contract code seems worthwhile.
fixes #1058

@erights I gave just a little thought to how to do this in SES... would you want the extra function call on all platforms? Or do feature detection? I'm not sure.

So this represents something that I know how to do. I'm interested in feedback on which alternative(s) we should pursue.

2021-08-04 23:00 UTC, kriskowal commented
It seems within the charter of SES to tame Object.freeze and I like your idea of doing feature detection to avoid the wrapper on platforms that don’t recognize the flag. The code here does the job just fine. Within SES, we’d `import { freeze } from './commons.js'`.

2021-08-04 23:26 UTC, warner commented
Does the XS `Object.freeze(obj, true)` only recurse on properties? Is that what Peter(?) meant by "it doesn't do anything that userspace couldn't already do"? That sort of extra behavior isn't a threat: adversarial code can already walk an API object's properties. The real threat is if e.g. closed-over mutable state becomes frozen, or the contents of a Map.

Do we know if that's what the XS `freeze` does? Should the unit test for this patch exercise that behavior too?

That said, this change looks fine, and simply preventing the extra arguments from making it through should tame `freeze` enough for our needs. And, I'm +1 to @kriskowal 's thought that this could live in SES instead (or in addition to).

2021-08-04 23:29 UTC, phoddie commented
> Does the XS Object.freeze(obj, true) only recurse on properties?

Correct.

> Is that what Peter(?) meant by "it doesn't do anything that userspace couldn't already do"? 

Yes.

> That sort of extra behavior isn't a threat: adversarial code can already walk an API object's properties

That was my point.

2021-08-04 23:40 UTC, erights commented
@phoddie What does it do when it encounters a function with captured lexical variables?

What does it do with, for example, a Date object?

What does it do when it encounters an accessor property? A proxy object? A map or weakMap?

If it has the semantics of `harden`, that would be hugely beneficial to us. Before the patching of `Object.prototype.freeze` that @dckc is doing here, we'd first save it off to the side to be our harden. So please *do not* bother to make a configuration omitting it, at least not on our account.

2021-08-04 23:44 UTC, erights requested changes
I like your feature detecting plan. Please do that. Thanks!

2021-08-05 00:09 UTC, phoddie commented
@erights - I posted an example yesterday that showed private fields remain mutable after using our deep freeze. Here is an example for `Date`, as requested:

```js
const d = new Date;
trace(d, "\n");
Object.freeze(d, true);
d.setHours(0);
d.setMinutes(0);
d.setSeconds(0);
trace(d, "\n");
d.foo = 12;
```

The output is:

```
Wed Aug 04 2021 17:08:25 GMT-0700
Wed Aug 04 2021 00:00:00 GMT-0700
$moddable/examples/helloworld/main.js (26) # Break: ?: set foo: not extensible!
```

2021-08-05 00:12 UTC, erights commented
Hi @phoddie our `harden` implementation is at https://github.com/endojs/endo/blob/master/packages/ses/src/make-hardener.js

Does it seem to have the same semantics? Should your deep freeze be a drop in replacement? What differences do you see?

2021-09-08 22:26 UTC, kriskowal commented
Tracking https://github.com/endojs/endo/issues/882

2022-02-02 01:28 UTC, kriskowal commented
I’ve sized this on the assumption of some separate preparatory work:
- https://github.com/endojs/endo/issues/681
- https://github.com/endojs/endo/issues/1001

2022-02-03 16:17 UTC, Tartuffo commented
@kriskowal This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, wallet, zoe contract

2022-02-03 22:35 UTC, kriskowal commented
@dckc I’ve moved tracking for taming to endo endojs/endo#882 and given that I won’t have a solution there immediately, I don’t object to doing a redundant round of feature-detection-and-taming here in xsnap. If you wish to pursue that, I can offer a review or take-over here. Otherwise, I think we can close this PR.

2022-02-03 23:41 UTC, dckc commented
it's better done after migrating xsnap to endo.

2022-02-03 23:41 UTC, closed without merging