refactor(solo): Convert RESM to NESM
Agoric/Agoric pull request #3619
Opened 2021-08-07 00:12 UTC by kriskowal

This subsumes a trivial upgrade for dapp-svelte-wallet necessary for its functioning.

Refs #527

2021-08-09 21:05 UTC, michaelfig requested changes
https://github.com/Agoric/agoric-sdk/pull/3619/checks?check_run_id=3266996850#step:8:205 indicates a problem with:

```console
$ rg entrypoint.cjs
[...]
./packages/agoric-cli/lib/start.js
116:    agSolo = path.resolve(__dirname, '../../solo/src/entrypoint.cjs');
```

2021-08-09 21:05 UTC, michaelfig commented on packages/solo/src/web.js
> +import morgan from 'morgan';
I had to test this manually, but yes, it works.  Thanks for the simplification!

2021-08-09 21:06 UTC, michaelfig approved these changes
CI will keep you honest.  No need to request changes.

2021-08-09 21:08 UTC, michaelfig requested changes
No, CI doesn't keep you honest when targeting a PR on a branch.

2021-08-09 23:21 UTC, kriskowal commented
> No, CI doesn't keep you honest when targeting a PR on a branch.

CI will keep me honest before the code reaches master. The stacked diffs technique I’m using allows me to land the entire stack quickly using merge commits, once the top of the stack is immediately on top of the latest master. Once I have the whole stack reviewed, I can get the entire stack through CI in one round trip (while under a single Keybase lock on master), then land each PR without triggering a re-run of CI between each.

With an approval, I could accidentally merge this into the base branch, but that will have to pass CI on top of the most recent master too.

2021-08-10 00:55 UTC, kriskowal commented
Now at the head of the queue 😇

2021-08-10 18:27 UTC, michaelfig approved these changes

2021-08-12 01:18 UTC, merged