refactor(treasury): Convert RESM to NESM
Agoric/Agoric pull request #3645
Opened 2021-08-10 03:29 UTC by kriskowal

Refs #527

2021-08-10 18:33 UTC, katelynsills commented
I think @Chris-Hibbert is better suited for this review.

2021-08-10 20:23 UTC, Chris-Hibbert requested changes

2021-08-10 20:23 UTC, Chris-Hibbert commented on packages/treasury/test/test-bootstrapPayment.js
> +  const autoswapInstall = await makeInstall(await autoswapRoot, zoe);
This is  a non-top-level await. Is that going to be allowed? Can we put the await inside `makeInstall()` instead?

2021-08-10 20:23 UTC, Chris-Hibbert commented on packages/treasury/test/test-vault.js
> +  const contractPath = new URL(await importMetaResolve(sourceRoot, import.meta.url)).pathname;
await is not top-level here.

2021-08-11 23:04 UTC, Chris-Hibbert approved these changes
LGTM!

2021-08-12 01:25 UTC, merged