chore(install-ses): export types
Agoric/Agoric pull request #3919
Opened 2021-10-01 20:04 UTC by ctjlewis

Doing:

```ts
import '@agoric/install-ses'
harden({});
```

Throws a TypeError because there is no type information letting us know statically that `harden` and `lockdown` are now available as globals as a side effect of `import 'ses'` in that package.

This change simply converts `import 'ses'` to `export * from 'ses'` which produces no runtime changes (unless they add exports—which I think it would be fine to re-export) and makes sure types are available.

2021-10-06 00:09 UTC, michaelfig requested changes
Thanks for this contribution!  I'm always happy to see better typing.

Just one minor nit wrt import ordering then once tests pass I'd be happy to merge.

2021-10-06 00:09 UTC, michaelfig commented on packages/install-ses/install-ses.js
> -import 'ses';
Please keep these lines, as the order of the imports matters (or at least *will* matter when #3891 lands).

I think it's fine to have both an `import` and `export` directive with the same `'ses'` module specifier.

2021-10-06 02:30 UTC, ctjlewis commented
@michaelfig Thanks! My only concern was, will the import and the export cause the side effects of SES to run twice? I know the shim will check if it has already run, but I was mostly thinking about performance.

Will push up changes and if you don't see this as an issue, it should be good to merge.

2021-10-06 02:43 UTC, michaelfig commented
> will the import and the export cause the side effects of SES to run twice? I know the shim will check if it has already run, but I was mostly thinking about performance.

Actually, multiple `imports` (or `export from`s) for the same specifier (such as `'ses'`) are defined in ESM to only evaluate the referenced module once and return the same instance for all of those import/exports.  So, no worries about performance, but it is still worth commenting that we have ordering constraints with `ses` and still want to export all its types.

> Will push up changes and if you don't see this as an issue, it should be good to merge.

Sounds great!

2022-03-15 18:51 UTC, michaelfig commented
@ctjlewis thank you for this suggestion!

We've since incorporated it into a permanent home in our upstream [endojs/endo](https://github.com/endojs/endo/blob/master/packages/lockdown/pre.js#L8).  `@agoric/install-ses` has been replaced by `@endo/init` which uses `@endo/lockdown`.

Closing this PR, as the intent has been realised.

2022-03-15 18:51 UTC, closed without merging