try Michael's idea to harden arguments
Agoric/Agoric pull request #4353
Opened 2022-01-22 00:01 UTC by turadg

closes: #XXXX
refs: #XXXX

## Description

### Security Considerations

### Documentation Considerations

### Testing Considerations

2022-01-22 02:59 UTC, erights commented
My concern about this kind of thing is that it masks bugs; specifically bugs of unhardened undefensive objects inadvertently running around. OTOH, I've occasionally written such hardens in similar strategic places for convenience, even realizing they have the same cost.

When I find the time, I am trying to advance an experiment that will give us a much narrower, but still principled, notion of trust/defensiveness boundaries within our code that will enable us to `harden` much less without losing much of our confidence in our defensiveness. But we're not there yet.

2022-01-22 02:59 UTC, erights requested changes
My concern about this kind of thing is that it masks bugs; specifically bugs of unhardened undefensive objects inadvertently running around. OTOH, I've occasionally written such hardens in similar strategic places for convenience, even realizing they have the same cost.

When I find the time, I am trying to advance an experiment that will give us a much narrower, but still principled, notion of trust/defensiveness boundaries within our code. This will enable us `harden` much less without losing much confidence in our defensiveness. But we're not there yet.

2022-01-23 21:22 UTC, michaelfig commented
> My concern about this kind of thing is that it masks bugs; specifically bugs of unhardened undefensive objects inadvertently running around.

I've written up the practical motivation for this change in the description.  Can you please reread and reconsider?

2022-01-23 21:27 UTC, michaelfig commented
@erights, I think your concerns may partly be mitigated by the fact that now we have `Far`, so `harden` can't accidentally create remotables.

2022-01-23 21:55 UTC, erights approved these changes
Based on a verbal conversation with @michaelfig , this now LGTM!

There will be lots of fallout from the rationale for this, to be written...

2022-01-23 22:21 UTC, merged