style: prettier yaml
Agoric/Agoric pull request #4429
Opened 2022-02-01 16:03 UTC by turadg

## Description

Include .github and YAML files in prettier so we're consistent across developers. This is done using our current version of Prettier (1.9.1) but I confirmed that [2.5.1](https://github.com/Agoric/agoric-sdk/pull/4330) won't change them. 

### Security Considerations

None.

### Documentation Considerations

None, it's automatic.

### Testing Considerations

None.

2022-02-01 18:34 UTC, mhofman commented
Wondering if we should switch to a `.prettierignore` approach instead of whacking a mole with the glob pattern to align which files are included in peoples IDE, but not in the command line scripts.

I for one would also welcome including `.md` but that might be a little more invasive.

2022-02-01 18:36 UTC, mhofman requested changes
Approving, but putting a request change because I have a few workflow yml files changes in flight I'd prefer landing first.

2022-02-01 19:32 UTC, turadg commented
> Wondering if we should switch to a .prettierignore approach instead of whacking a mole with the glob pattern to align which files are included in peoples IDE, but not in the command line scripts.

Yep, once we have https://github.com/Agoric/agoric-sdk/pull/4330 we can drop the globs and provide the root directories. In 1.x you have to glob.

> I for one would also welcome including .md but that might be a little more invasive.

Ditto. When I ran it many files changed quite a bit so it'll need wider agreement.

2022-02-02 22:03 UTC, mhofman approved these changes

2022-02-02 22:04 UTC, merged