experiment: refactor vault to API of virtual objects
Agoric/Agoric pull request #4697
Opened 2022-02-28 22:11 UTC by turadg

_no ticket_

## Description

For consideration of doing before Restival until we can fully virtualized the run-protocol objects. This introduces a `nonvirtualStore` that has a `defineKind` that matches the same API but without the virtualization abiltiies.

### Security Considerations

### Documentation Considerations

### Testing Considerations

2022-03-01 00:32 UTC, dtribble reviewed
WIP but great start

2022-03-01 00:32 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +    zcf,
shouldn't be persistent state

2022-03-01 00:32 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +    runMint,
runMint, priceAuthority, etc should probably come from manager

2022-03-01 00:32 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +const actualize = state => {
`actualize` is a really terrible name :)

2022-03-01 00:32 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +  let outerUpdater;
shouldn't this be persistent state?

2022-03-01 00:32 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +   * @param {Amount<NatValue>} newDebt - principal and all accrued interest
<NatValue> is going to get tiresome real quick, given that it's pervasive for fungible tokens.

2022-03-01 00:32 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +    runSnapshot: AmountMath.makeEmpty(runMint.getIssuerRecord().brand, 'nat'),
we slid into naming things for "run".  This should be `debtSnapshot` or `debt`

2022-03-01 00:32 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +    const { manager, priceAuthority } = state;
cute!

2022-03-01 00:32 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +        run: state.runSnapshot,
need to rename `run`

2022-03-01 00:32 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +    updateDebtSnapshot(AmountMath.makeEmpty(runBrand, 'nat'));
what is 'nat'?  This is not the pattern we use elssewhere

2022-03-01 00:32 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +    return transferInvitationHook;
This is named wrong.  This method is "(makeTransferInvitation)Hook", not "make(TransferInvitationHook)"

2022-03-01 00:32 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +export const makeInnerVault = defineKind('innerVault', init, actualize);
I think outervault also needs to be durable

2022-03-01 01:02 UTC, dtribble requested changes
A few more comments. Between these two reviews, the explicit typing for NatValue and the naming of the hooks need to be addressed. The basic transforamtion all looks great.

2022-03-01 01:02 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +      state.manager.getCompoundedInterest(),
use the const pattern to extract state?

2022-03-01 01:02 UTC, dtribble commented on packages/run-protocol/src/vaultFactory/vault.js
> +  return harden({
I'm surprised this should be`harden`ed given that it represents mutable state.

2022-03-08 00:38 UTC, turadg commented
Experiment concluded. Most of this made it into another PR

2022-03-08 00:38 UTC, closed without merging