fix(zoe): fix auction makeBidInvitation
Agoric/Agoric pull request #4899
Opened 2022-03-23 07:50 UTC by samsiegart

fixes: https://github.com/Agoric/dapp-card-store/issues/50

2022-03-24 04:03 UTC, erights requested changes

2022-03-24 04:03 UTC, erights commented on packages/zoe/src/contracts/auction/index.js
>      return harden({
Your use of `await` nested within an expression violates our `await` design rule. This code is a good example of why. Looking at this code, is it clear whether `sellerProposal.want.Ask` and `getCurrentBids()` are evaluated before or after the `await` point?

Instead, if you want to use `await` here, I suggest you rename the variable that might hold a promise for a time authority to something else, and then await it at function top level to obtain the non-promise time authority variable.

```suggestion
    const timeAuthority = await timeAuthorityP;
    return harden({
```

2022-03-24 04:03 UTC, erights commented on packages/zoe/src/contracts/auction/index.js
> +      timeAuthority: await timeAuthority,
```suggestion
      timeAuthority,
```

2022-03-24 04:03 UTC, erights commented on packages/zoe/src/contracts/auction/index.js
> +    const customProperties = await getSessionDetails();
This one is good.

2022-03-24 04:03 UTC, erights commented on packages/zoe/test/unitTests/contracts/test-auction.js
> +          timeAuthority: Promise.resolve(timer),
I don't understand the purpose of this. Why wrap the `timer` in a promise? I'm equally confused by the other examples below.

2022-03-29 04:53 UTC, samsiegart commented
@erights Thanks for reviewing. Your feedback about the `await` design rule was helpful. I was wrapping the timer in a promise in the tests to mirror the fact that it was being passed in as a promise in production (causing the contract to break). That way, the tests fail without the fixes to the contract in this PR.

However, I think I'd like to close this PR in favor of https://github.com/Agoric/dapp-card-store/pull/51 since it's simpler.

2022-03-29 04:53 UTC, closed without merging