refactor: Add a buffered StorageAPI helper
Agoric/Agoric pull request #5294
Opened 2022-05-04 23:48 UTC by gibson042

As suggested at https://github.com/Agoric/agoric-sdk/pull/5258#discussion_r863276862

## Description

This PR extends #5292, and lays some groundwork for #4558. c67df20001ff1a034a50d3807e0ce1e687492c7f is the most relevant commit.

### Security Considerations

None that I can see.

### Documentation Considerations

As commented, I wonder if StorageAPI functions should be extracted into their own module.

### Testing Considerations

`makeBufferedStorage` really should be tested. Any pointers on a good analog?

2022-05-04 23:49 UTC, gibson042 commented on packages/cosmic-swingset/src/chain-main.js
> +      throw new Error('not implemented');
I'm expecting to introduce this for #4558.

2022-05-05 01:20 UTC, FUDCo approved these changes
Seems legit.

2022-05-05 22:05 UTC, warner requested changes
The way swingset manages the kvStore is pretty old and creaky, so refactoring is welcome. That said, I'm slightly skeptical that swingset is a good source for a generic "buffered KV store" library (as your "should this live in a different package?" comment notes). And I don't really understand how cosmic-swingset uses its own buffering layer, so I can't effectively argue for or against sharing an implementation. I'm not excited about deep imports (it imposes hidden constraints on future internal refactoring). But most of those concerns might go away if this moved into a separate package some day.

So I guess I'm -0 on the change.. it's a good refactoring, it feels slightly weird, but it's probably a net win overall.

The activityhash write sequencing definitely needs to change to match the previous commit boundaries. Our tests on activityhash should be observing the writes made to the backing store.. if they aren't, we should improve them, and maybe they should also test two cranks in a row (which might have caught the inclusion of activityhash in the hash).

2022-05-05 22:05 UTC, warner commented on packages/SwingSet/src/kernel/state/storageWrapper.js
> +    // Store the new activityhash.
By using the buffered kvStore for this following `kvStore.set('activityhash')`, the hash gets put into the pending buffer, not the actual store. To match the previous behavior, I think this needs an additional commit() call afterwards, or perhaps it'd be safe to move the one `commit()` from the start of this method to the end.

Also, we haven't been including the `set('activityhash')` in the activityhash itself. I don't know how to best achieve that with this new layering.. making `onPendingSet` ignore the one key feels weird.

2022-05-06 15:03 UTC, gibson042 commented on packages/SwingSet/src/kernel/state/storageWrapper.js
> +    // Store the new activityhash.
`kvStore` in this scope is the backing StorageAPI instance, not the `crankBuffer` wrapping it. These bindings are identical to those currently in `buildCrankBuffer`, and so is the call sequencing AFAICT.

**Current**: https://github.com/Agoric/agoric-sdk/blob/6a5f377c5ba115576a0e813cc6266039452732c0/packages/SwingSet/src/kernel/state/storageWrapper.js
* [`crankBuffer.set()`](https://github.com/Agoric/agoric-sdk/blob/6a5f377c5ba115576a0e813cc6266039452732c0/packages/SwingSet/src/kernel/state/storageWrapper.js#L148) and [`crankBuffer.delete()`](https://github.com/Agoric/agoric-sdk/blob/6a5f377c5ba115576a0e813cc6266039452732c0/packages/SwingSet/src/kernel/state/storageWrapper.js#L163) update `additions` and `deletions` and feed consensus-relevant data to `crankhasher`.
* [`commitCrank()`](https://github.com/Agoric/agoric-sdk/blob/6a5f377c5ba115576a0e813cc6266039452732c0/packages/SwingSet/src/kernel/state/storageWrapper.js#L182) sends a sequence of calls to the backing `kvStore`:
  1. `kvStore.set(key, value)` for each addition
  2. `kvStore.delete(key)` for each deletion
  3. `oldActivityhash = kvStore.get('activityhash')`
  4. `kvStore.set('activityhash', activityhash)`, where `activityhash` is a digest of data including `oldActivityhash` and `crankhasher.digest()` (before the replacement of `crankhasher` between steps 2 and 3).

**Proposed**: https://github.com/Agoric/agoric-sdk/blob/45406c68018b36f94cfd5cd380be888ca31ed3ac/packages/SwingSet/src/kernel/state/storageWrapper.js
* `crankBuffer.set()` and `crankBuffer.delete()` update `additions` and `deletions` [_[buffered storage `set()` and `delete()`](https://github.com/Agoric/agoric-sdk/blob/45406c68018b36f94cfd5cd380be888ca31ed3ac/packages/SwingSet/src/lib/storageAPI.js#L125-L136)_] and feed consensus-relevant data to `crankhasher` [_[`buildCrankBuffer` behavior via buffered storage `onPendingSet` and `onPendingDelete`](https://github.com/Agoric/agoric-sdk/blob/45406c68018b36f94cfd5cd380be888ca31ed3ac/packages/SwingSet/src/kernel/state/storageWrapper.js#L46-L63)_].
* [`commitCrank()`](https://github.com/Agoric/agoric-sdk/blob/45406c68018b36f94cfd5cd380be888ca31ed3ac/packages/SwingSet/src/kernel/state/storageWrapper.js#L73) sends a sequence of calls to the backing `kvStore`:
  1. `kvStore.set(key, value)` for each addition and then `kvStore.delete(key)` for each deletion [_in [buffered storage `commit()`](https://github.com/Agoric/agoric-sdk/blob/45406c68018b36f94cfd5cd380be888ca31ed3ac/packages/SwingSet/src/lib/storageAPI.js#L190)_]
  2. `oldActivityhash = kvStore.get('activityhash')`
  3. `kvStore.set('activityhash', activityhash)`, where `activityhash` is a digest of data including `oldActivityhash` and `crankhasher.digest()` (before the replacement of `crankhasher` after step 1).


I've added clarifying comments: https://github.com/Agoric/agoric-sdk/blob/80afe8640d8e683e729eed3bc809bb04c5551280/packages/SwingSet/src/kernel/state/storageWrapper.js#L81-L98

2022-05-27 03:03 UTC, warner approved these changes
Tentatively approving. Please get @michaelfig 's opinion on the chain-main.js changes to make sure I didn't miss something, and please find a way to write a test for it. `packages/SwingSet/test/test-state.js` has tests for `buildCrankBuffer`, maybe you could crib something from there to build a new `packages/cosmic-swingset/test/test-chain-storage.js`.

2022-05-27 03:03 UTC, warner commented on packages/SwingSet/src/lib/storageAPI.js
> +      if (onGet !== undefined) onGet(key, value);
is there any particular reason to not use `if (onGet) onGet(key, value)` ?

2022-05-27 03:03 UTC, warner commented on packages/cosmic-swingset/src/chain-main.js
> +      buffered.set(key, value);
I can't quite trace what's happening here. There's a weird property that I think we need to maintain: if the caller does `x = s.get('foo'); x.prop = 'changed'; s.commit()`, then we need to write back the modified `.prop` to the backing store. (I'm embarrassed that this seems to be necessary, and I'm sure that it's because I made a really weird API for the original mailbox structure, and my only defense is that this was some of the earliest Swingset code ever written).

Does this code maintain that property? I can tell there's a cache here at this level (`storage`), and a buffer of pending writes at the `makeBufferedStorage` level, but I'd like the expert to tell me if this `buffered.set` is sufficient to get the same value into both places.

I like `makeBufferedStorage` on the swingset side, it seems like a nice refactoring. I'm a little dubious about the utility using it here if maintaining that funky mutable-read-data behavior requires something weird. But if it works, and it supports the next phase of your work, I'm ok with it.

I *would* feel better if there were tests on this code, and I believe there are not. `makeBufferedStorage` should be testable within swingset, and this `storage` definition should be testable in isolation (from swingset and from the chain's backing store).

2022-05-27 03:04 UTC, warner commented on packages/SwingSet/src/kernel/state/storageWrapper.js
> +    // Store the new activityhash.
Ah, gotcha, I was confused by the overlapping names (and I never remember which way around JS's destructuring assignment works). The extra comments helped a lot.

2022-06-06 21:36 UTC, michaelfig commented
I'd like to test this PR against actual chain+ag-solo, but I think I have to wait for you, @gibson042, to resolve the conflicts and bring up-to-date with current master.

2022-06-06 22:04 UTC, gibson042 commented on packages/SwingSet/src/lib/storageAPI.js
> +      if (onGet !== undefined) onGet(key, value);
No, the behavior would be equivalent either way. Is the coercing form preferred?

2022-06-06 22:26 UTC, gibson042 commented on packages/cosmic-swingset/src/chain-main.js
> +      buffered.set(key, value);
> Does this code maintain that property?

The short answer is "yes". This `onGet` configuration for the `makeBufferedStorage` call that wraps the `chainSend()`-backed storage interface results in every `get(key)` call on the returned storage interface being immediately followed with a `set(key, fetchedValue)` that adds a reference to its `additions` map (where `commit()` will find it and translate to a `set(key, valueWithAnyMutations)` against the `chainSend()`-backed storage—which performs its own translation to a stringified {method: 'set', key, value} message).

2022-06-07 02:06 UTC, michaelfig approved these changes
Great stuff!

2022-06-07 03:56 UTC, merged