test: metrics subscription testing support
Agoric/Agoric pull request #5402
Opened 2022-05-19 23:11 UTC by turadg

## Description

For the epic https://github.com/Agoric/agoric-sdk/issues/4639 we're creating many new subscription streams. We want them to all work consistently in the Inter Protocol. While working on https://github.com/Agoric/agoric-sdk/pull/5393 I found it worthwhile to make a support utility. This makes it available throughout the package.

It takes a public facet and requires that it have a method `getMetrics` to help enforce that convention.

### Security Considerations

non-prod

### Documentation Considerations

helps codify a nascent convention

### Testing Considerations

test utility itself

2022-05-19 23:19 UTC, turadg commented on packages/run-protocol/test/vaultFactory/test-vaultFactory.js
> +    collaterals: { 1: chit.brand },
since this is expresses changes, it has to reference the place in the array (`1:`)

2022-05-19 23:22 UTC, turadg commented on packages/run-protocol/test/vaultFactory/test-vaultFactory.js
> +  t.pass();
needed because otherwise there are no `t` assertions and Ava warns

2022-05-19 23:28 UTC, Chris-Hibbert requested changes
In #4648 (metrics for AMM), I have `getMetrics()` for the top-level pools, but `getPoolMetrics(brand)` to get the metrics subscriptions for each of the individual pools. Is there any chance we can make a helper that will support both?

2022-05-19 23:28 UTC, Chris-Hibbert commented on packages/run-protocol/test/vaultFactory/test-vaultFactory.js
> +  t.pass();
I'd prefer to pass t into `metricsTracker()`, and have it use `t.is()` rather than `assert`.

2022-05-20 16:32 UTC, Chris-Hibbert approved these changes
Nice!  thanks.

2022-05-20 18:35 UTC, dckc commented
metrics seems like a confusing name.

metrics are usually low level stuff, like prometheus. not contract stuff

2022-05-20 20:40 UTC, merged

2022-05-20 21:46 UTC, turadg commented
> metrics are usually low level stuff, like prometheus. not contract stuff

To my mind, metrics are whatever you're measuring. We have sprint metrics. We have business metrics.

Open to another name if you want to suggest one.

2022-05-20 22:44 UTC, dckc commented
I guess I can deal with "metrics" meaning one thing in `packages/run-protocol` and another thing in `packages/SwingSet`, especially since I don't have another one to suggest. I'm hesitant to speak for the rest of the team, though. hm.