Add addPool to AMM creatorFacet and reinstate economy boot
Agoric/Agoric pull request #5428
Opened 2022-05-25 05:27 UTC by michaelfig

refs: #5375

## Description

- Put addPool on the AMM creatorFacet.
- Fix economy bootstrap, and add to CI.

### Security Considerations

### Documentation Considerations

### Testing Considerations

2022-05-25 13:10 UTC, turadg commented on packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
> +  // TODO: pass this into makeAddPoolInvitation
I think this should be done before merge to DRY out the two addPools. They've already diverged in that [the other one updates metrics](https://github.com/Agoric/agoric-sdk/blob/0f4e0b53ffea8ea608f200752d8d342c0a2ce332/packages/run-protocol/src/vpool-xyk-amm/addPool.js#L97). cc @Chris-Hibbert

2022-05-25 13:10 UTC, turadg commented on packages/run-protocol/src/vpool-xyk-amm/addPool.js
> +        await zcf.saveIssuer(secondaryIssuer, keyword);
noting https://github.com/Agoric/agoric-sdk/issues/5407 to link this instance to that ticket

2022-05-25 21:16 UTC, Chris-Hibbert requested changes
This makes it possible to create a new empty pool, violating the requirement for a minimum funding. It also allows/requires the pool to be funded using `addLiquidity` rather than going through `addPoolAndLiquidityHandler`, which means that no liquidity will be extracted to the reserve.

2022-05-25 21:34 UTC, dckc commented
@Chris-Hibbert , this no-fee `addPool` method is primarily intended to un-tie knots in automated bootstrap; it's not intended for normal production use. (I clarified the PR description to say as much.)

> This makes it possible to create a new empty pool, violating the requirement for a minimum funding.

The motivation for minimum funding was essentially spam prevention, wasn't it? This no-fee `addPool` method is on the creator facet, which is only available to the BLDer DAO, not to spammers. There's nothing inherently wrong with an empty AMM pool, is there?

> It also allows/requires the pool to be funded using `addLiquidity` rather than going through `addPoolAndLiquidityHandler`, which means that no liquidity will be extracted to the reserve.

Yes, this is a consideration that anyone with access to the AMM creator facet should be aware of. Is it a reason not to add the feature, though?

2022-05-25 22:16 UTC, dckc commented
try PSM?
try 0 minimum required liquidity?

2022-05-26 16:53 UTC, dckc commented
obsolete in favor of #5441

2022-05-26 16:53 UTC, closed without merging