Implement smart-wallet and read-only UI
Agoric/Agoric pull request #5594
Opened 2022-06-14 21:17 UTC by michaelfig

closes: #5356

## Description

Here's a (rather unimpressive) working demonstration of the smart wallet UI.  Notice the zero-latency initialization of the view, and that it's currently read-only.

https://user-images.githubusercontent.com/457244/173690436-b93d6014-5ab7-4f53-966d-aa9fc72dc5e1.mov

### Security Considerations

### Documentation Considerations

### Testing Considerations

2022-06-16 02:21 UTC, dckc requested changes
found a critical problem

2022-06-16 02:21 UTC, dckc commented on packages/vats/src/core/basic-behaviors.js
> +        { agoricNames, bank, namesByAddress, myAddressNameAdmin, board },
Both the `smartWallet` contract an `ag-solo` use `myAddressNameAdmin` to set up `depositFacet`. There can be only one. This is why we see 0 invitations in xnet https://github.com/Agoric/agoric-sdk/issues/5513#issuecomment-1156612543 .

2022-06-29 21:41 UTC, turadg requested changes

2022-06-29 21:41 UTC, turadg commented on packages/wallet/contract/src/smart-wallet.js
> +export const start = async (zcf, privateArgs) => {
we need some test of this contract starting and the shape of its `creatorFacet`. I can help with that if you like.

2022-06-29 21:41 UTC, turadg commented on packages/wallet/api/src/lib-wallet.js
> +  /** @typedef {any} AttestationTool */ /* @@@ TODO */
before landing or after?

2022-07-07 16:21 UTC, dckc commented
overtaken by #5701 etc.

2022-07-07 16:21 UTC, closed without merging