fix(wallet-ui): safely render invalid amount values
Agoric/Agoric pull request #5617
Opened 2022-06-16 23:12 UTC by samsiegart

fixes: https://github.com/Agoric/agoric-sdk/issues/5553

2022-06-17 13:31 UTC, turadg requested changes

2022-06-17 13:31 UTC, turadg commented on packages/wallet/ui/src/components/Offer.jsx
> +
this block is for transforming an amount to a string. I think that would be useful outside this module. It also should be thoroughly tested with different amount cases, including failure. 

```suggestion
    const valueString = stringifyAmount(amount);
```

2022-06-17 13:31 UTC, turadg commented on packages/wallet/ui/src/components/Offer.jsx
> +  }
isn't this also an amount? why repeat this logic?

if it's for data validation that should happen on the way into application state.

2022-06-17 13:31 UTC, turadg commented on packages/wallet/ui/src/components/tests/Offer.test.jsx
> +test('renders unknown amounts when parsing fails', () => {
if you had `stringifyAmount` you wouldn't need to do all this React stuff just to be testing that "unknown" is the string for an amount that fails to parse.

2022-06-17 13:31 UTC, turadg commented on packages/wallet/ui/src/components/tests/Offer.test.jsx
> +  expect(give.text()).toContain('unknown');
is this accurate? this appears to the user like the system doesn't know the value. the system does but the UI encountered an error rendering it. We'd want bug reports in that case? If so, something like `<error>` would be better.

2022-06-17 13:31 UTC, turadg commented on packages/wallet/ui/src/components/Offer.jsx
> +      console.warn("Couldn't parse amount value for", pursePetname, amount);
some part of UX will be broken (seeing the value) so this is an `error`

2022-06-17 14:03 UTC, samsiegart commented on packages/wallet/ui/src/components/tests/Offer.test.jsx
> +  expect(give.text()).toContain('unknown');
Do you mean wrap each amount in something like https://github.com/Agoric/dapp-treasury/blob/main/ui/src/components/ErrorBoundary.jsx? Then if it fails to parse we'll see a proper error message rather than `unknown`.

2022-06-17 14:03 UTC, samsiegart commented on packages/wallet/ui/src/components/Offer.jsx
> +  }
Will fix this up to reuse logic.

I don't think it should be considered as data validation, we're just trying our best to render something we got from the backend, the UI doesn't create this value.

2022-06-17 17:00 UTC, turadg commented on packages/wallet/ui/src/components/tests/Offer.test.jsx
> +  expect(give.text()).toContain('unknown');
I meant simply `toContain('<error>')` as the string. an ErrorBoundary is a good idea though, to make the app more robust. I think this particular parsing error made the app crash.

2022-06-19 21:34 UTC, samsiegart commented
I redid this PR to make it just use an error boundary instead of special rendering logic (see screenshots in description). PTAL.

2022-06-20 14:05 UTC, turadg approved these changes
Good idea to solve the crashing problem more generally with an error boundary.

Noted some non-blocking code quality improvements.

2022-06-20 14:05 UTC, turadg commented on packages/wallet/ui/src/components/Proposal.jsx
> +
these don't need any of the values of the enclosing function so should be in module scope.

2022-06-20 14:05 UTC, turadg commented on packages/wallet/ui/src/components/Proposal.jsx
> +  const Want = entry => OfferEntry(entryTypes.want, entry);
it looks like OfferEntry can also be module scope, so this can too.

Then consider a helper to give you the values you need on 94 and 95.

```
const gives = offerEntries(offer.proposalForDisplay.give);
const wants = offerEntries(offer.proposalForDisplay.want);
```

2022-06-20 14:05 UTC, turadg commented on packages/wallet/ui/src/components/Proposal.jsx
> +  const wants = Object.entries(want).sort(([kwa], [kwb]) => cmp(kwa, kwb));
Not used until line 94. Don't define until needed, so that the reader has less to keep track of while studying the function.

2022-06-20 14:05 UTC, turadg commented on packages/wallet/ui/src/components/Proposal.jsx
> +          <pre>{JSON.stringify(args, null, 2)}</pre>
TIL `spacer` argument

2022-06-20 14:05 UTC, turadg commented on packages/wallet/ui/src/components/Proposal.jsx
> +      {args !== undefined && (
are other falsy values valid arguments?

2022-06-20 17:26 UTC, samsiegart commented on packages/wallet/ui/src/components/Proposal.jsx
> +      {args !== undefined && (
They shouldn't be according to this https://agoric.com/documentation/zoe/api/zoe.html#offerargs

However, I think it makes sense to render them for debugging purposes either way.

2022-06-20 17:29 UTC, samsiegart commented
I just refactored some functions into the module scope as suggested. Thanks for review!

2022-06-20 18:08 UTC, merged