refactorings to support new smart wallet
Agoric/Agoric pull request #6128
Opened 2022-09-04 00:46 UTC by turadg

Plucked from https://github.com/Agoric/agoric-sdk/pull/6084

## Description

- feat(governance): return completedBallet cc @Chris-Hibbert 
- refactor(governance): validate offerArgs cc @Chris-Hibbert 
- feat(bootstrap): produce testFirstAnchorKit cc @dckc 
- docs
- refactor(vats): bundle-legacy-walletFactory cc @dckc 

### Security Considerations

`testFirstAnchorKit` exposes the IssuerKit for the anchor token into the bootstrap space. Anyone who can consume that can mint, but anyone who can consume bootstrap can do much worse! IOW, it's a highly trusted capability to consume the bootstrap space. (In this case it's needed for tests covering bootstrap.)

### Documentation Considerations

### Testing Considerations

2022-09-05 18:59 UTC, Chris-Hibbert requested changes
the `@returns` change seems important. The capitalization is just a nit.

This seems fine.  Telling the voter how many votes they cast will be helpful in other counters.

2022-09-05 18:59 UTC, Chris-Hibbert commented on packages/governance/src/binaryVoteCounter.js
> +    return completedBallot;
This should require adding an `@returns` clause to `SubmitVote`, right?

2022-09-05 18:59 UTC, Chris-Hibbert commented on packages/governance/src/committee.js
> +            const continuingVoteHandler = (cseat, offerArgs) => {
```suggestion
            const continuingVoteHandler = (cSeat, offerArgs) => {
```

2022-09-05 19:04 UTC, dckc reviewed
the parts I'm asked to review look fine.

2022-09-05 19:04 UTC, dckc commented on packages/vats/test/devices.js
> +import bundleWalletFactory from '../bundles/bundle-legacy-walletFactory.js';
very well.

2022-09-05 19:04 UTC, dckc commented on packages/inter-protocol/src/proposals/startPSM.js
> +    produce: { testFirstAnchorKit: true },
very well, as we discussed

2022-09-06 16:24 UTC, Chris-Hibbert approved these changes

2022-09-06 17:31 UTC, merged