fix device timer remove()
Agoric/Agoric pull request #6262
Opened 2022-09-19 17:54 UTC by turadg

## Description

Working on https://github.com/Agoric/agoric-sdk/pull/6256 I noticed the condition in the loop was looking for a value that couldn't be in the array. I think this resulted in a bug in `TimerMap.remove` and thus `DeviceTimer.removeWakeup`.

### Security Considerations

Without this, wake handlers aren't removed from the map. PSMO uses timers for voting so this creates a resource exhaustion risk, proportional to the number of questions posed.

### Documentation Considerations

--
### Testing Considerations

No tests failed. What would a good regression test be?

2022-09-19 18:53 UTC, warner commented
The new vat-timer.js only ever exposes a single handler function to device-timer.js . The device has some other bugs that needed fixing, and I wanted to touch as little code as possible, so when I rewrote vat-timer to be durable, I also constrained the way it uses the device, to avoid those bugs without actually changing the device. So while this patch is probably correct and good, I think we don't strictly need it now.

2022-09-19 18:58 UTC, Chris-Hibbert approved these changes
LGTM.  Of course, @warner is the expert.

2022-09-19 21:26 UTC, warner commented
Are we sure this change would be correct? I'm looking at `eventsFor()` and `add()`, and:
* `add()` takes a `handler` (a remote object with a `.wake` method)
* `add()` does `const handlerRecord = { handler }` or `{ handler, index: repeater }`
* `add()` does `const { handlers: records } = eventsFor(time)`
  * `eventsFor()` pushes a `newRecord = { time, handlers: [] }` onto `schedule, and returns `newRecord`
* `add()` does `records.push(handlerRecord)`, then `schedule.sort`

So `schedule[i] = { time, handlers }`, and `handlers[n] = { handler, index? }`.

Then `remove` walks `schedule[i]` to look at the `{ time, handlers }` of each. If `handlers.length === 1`, it tests `handlers[0].handler === targetHandler`, which matches the shape above. If it's longer, it walks `for (const { handler } of handlers)` and compares each against `targetHandler`, which also matches the shape above.

I think the confusion stems from a `schedule[i].handlers` that should really be named `schedule[i].handlerRecords`. Then we'd have `schedule[i].handlerRecords[j].handler` to compare against `targetHandler`. The loop being patched is really iterating over handlerRecords, each of which has a `handler` property.

I'll agree that testing here is lacking. `packages/SwingSet/test/timer-device/bootstrap.js` is where this ought to be tested, and it currently only does a single wakeup per moment (`D(devices.timer).setWakeup(3n, handler)`), where to exercise this it needs to submit two separate handlers for the same moment.

2022-09-19 22:55 UTC, turadg commented
> Are we sure this change would be correct?

Simple proof that the current behavior is wrong:
https://github.com/Agoric/agoric-sdk/blob/e73f693a3ccb83ee7e1eb0bb0c277b2164b3083b/packages/SwingSet/src/devices/timer/device-timer.js#L149-L150

The element being searched by `indexOf` was a property of an element of the array, not the element itself.

I agree the confusion stems from naming. That's part of where static type checking shines, because it can't get thrown off by things appearing the same. It's job is to do all the analysis above automatically all the time for us.

Since we have `noImplicitAny: false` and a lot of `any` throughout the codebase, it does take some manual validation.

Now is the change here correct? I think so. The reason I think `removeWakeup` takes `IndexHandler` is [the one call to it](https://github.com/Agoric/agoric-sdk/blob/0032e11b92abc82d5422908273310f12cf2d41c0/packages/SwingSet/src/vats/timer/vat-timer.js#L327) matches the shape, [with a `wake` property](https://github.com/Agoric/agoric-sdk/blob/0032e11b92abc82d5422908273310f12cf2d41c0/packages/SwingSet/src/vats/timer/vat-timer.js#L887-L890).

So `targetHandler` is an `IndexedHandler`, as is `handlers` from Event that is at `schedule[i]`.

2025-04-04 21:19 UTC, turadg commented on packages/SwingSet/src/devices/timer/device-timer.js
> +          if (handler.handler === target && handlers.indexOf(handler) !== -1) {
I don't know why it's checking for presence of the value it just got out of the iterator

2025-04-08 05:37 UTC, mhofman reviewed
I need to qualify the previously broken behavior. The tests will greatly help, I just want to run them before the fix.

2025-04-08 05:37 UTC, mhofman commented on packages/SwingSet/src/devices/timer/device-timer.js
> +          if (handler.handler === target && handlers.indexOf(handler) !== -1) {
Well that's concerning. Previously `handler` was the `handlerRecord.handler` which could never be present in the `handlers` array, so this condition would have never matched. I am wondering if we somehow never encountered a case where more than one handler appeared in the `handlers` list?

2025-04-08 19:35 UTC, mhofman requested changes
Checking why this hasn't been a concern, the reason is that the timer vat does the following:

```js
  const reschedule = () => {
    // the first wakeup should be in the future: the device will not
    // immediately fire when given a stale request
    const newFirstWakeup = firstWakeup(schedule);
    // idempotent and ignored if not currently registered
    D(timerDevice).removeWakeup(wakeupHandler);
    if (newFirstWakeup) {
      D(timerDevice).setWakeup(newFirstWakeup, wakeupHandler);
    }
  };
```

Which means it always removes the single handler it's using before adding a new schedule. That means we only ever have at most a single pending wake up schedule.

That said the remove logic is still wrong. I can push changes to fix.

2025-04-08 19:35 UTC, mhofman commented on packages/SwingSet/src/devices/timer/device-timer.js
> +          if (handler.handler === target && handlers.indexOf(handler) !== -1) {
Ok I see that the new test is tripping this case before the fix. As a matter of commit stacking, I would have preferred to see the commit adding the test marking it as `.failing`, and for the fix to remove the `.failing`.

2025-04-08 19:35 UTC, mhofman commented on packages/SwingSet/src/devices/timer/device-timer.js
> +          if (handler.handler === target && handlers.indexOf(handler) !== -1) {
I believe this is still incorrect. splicing an array while iterating over it will move the items such that the item following the one being sliced out will be skipped.

The only safe way is iterating in reverse using the index.

2025-04-08 20:05 UTC, mhofman approved these changes
Removing my request for changes now that I've addressed the issue, but given my changes, I'd like another set of eyes. @gibson042 PTAL.

2025-04-12 13:20 UTC, gibson042 approved these changes

2025-04-12 13:20 UTC, gibson042 commented on packages/SwingSet/src/devices/timer/device-timer.js
> +   * @param {number} [repeater]
We should probably just rename this `repeater` parameter to `index`.

2025-04-12 13:20 UTC, gibson042 commented on packages/SwingSet/src/devices/timer/device-timer.js
> +   * @param {Waker} target
Please keep the old name for this parameter; it's more clear. 
```suggestion
   * @param {Waker} targetHandler
```

2025-04-12 13:20 UTC, gibson042 commented on packages/SwingSet/src/devices/timer/device-timer.js
> +        schedule.splice(i, 1);
```suggestion
        // Splice out this element, preserving `i` so we visit any successor.
        schedule.splice(i, 1);
```

2025-04-12 13:20 UTC, gibson042 commented on packages/SwingSet/src/devices/timer/device-timer.js
>            droppedTimes.push(time);
It's current behavior that the return value can include duplicate times, but still potentially surprising. Please document in the JSDoc header, and if possible confirm that consumers behave correctly w.r.t. the possibility.

2025-05-27 23:28 UTC, gibson042 approved these changes

2025-05-28 00:02 UTC, merged