WIP: arb passable tools
Agoric/Agoric pull request #6296
Opened 2022-09-21 20:25 UTC by erights

closes: #XXXX
refs: #XXXX

## Description

### Security Considerations

### Documentation Considerations

### Testing Considerations

2022-10-04 18:35 UTC, gibson042 requested changes
Looks good after a few tweaks.

2022-10-04 18:35 UTC, gibson042 commented on packages/store/tools/arb-passable.js
> +      },
There are guides for `depthFactor` → `depthSize` at [Arbitraries](https://github.com/dubzzz/fast-check/blob/a6fd30cedbbcf32d2376a5eff2cfe2c4c7a6dc50/packages/fast-check/documentation/Arbitraries.md#depth-size-explained) and [Migration 2.x to 3.x](https://github.com/dubzzz/fast-check/blob/c2600091f0410b301142254cde5cc61cd0385f78/packages/fast-check/MIGRATION_2.X_TO_3.X.md#depthsize-the-new-name-for-depthfactor-%EF%B8%8F), but [`oneof` documentation](https://github.com/dubzzz/fast-check/blob/a6fd30cedbbcf32d2376a5eff2cfe2c4c7a6dc50/packages/fast-check/documentation/Arbitraries.md#:~:text=oneof) suggests that it is necessary anyway: "_probability to select the first arbitrary will increase as we go deeper in the tree_" (which I also confirmed manually).
```suggestion
      { withCrossShrink: true },
```

2022-10-04 18:35 UTC, gibson042 commented on packages/store/tools/arb-passable.js
> +  fc.record({}),
Given the increasing weight applied to the first `oneof` option with depth and its preference in shrinking, this should be something which minimizes cognitive burden. `{}` isn't bad, but would a primitive (or even a particular primitive such as `null` or `""`) be better?

2022-10-04 18:35 UTC, gibson042 commented on packages/store/tools/arb-passable.js
> +        )
This can be reorganized now that we know more about `oneof`.
```suggestion
      // A tagged value, either of arbitrary type with arbitrary payload
      // or of known type with arbitrary or explicitly valid payload.
      // Ordered by increasing complexity.
      fc
        .oneof(
          fc.record({ type: arbString, payload: tie('arbDag') }),
          fc.record({
            type: fc.constantFrom('copySet'),
            payload: fc.oneof(
              tie('arbDag'),
              // copySet valid payload is an array of unique passables.
              fc.uniqueArray(tie('arbDag')),
            ),
          }),
          fc.record({
            type: fc.constantFrom('copyBag'),
            payload: fc.oneof(
              tie('arbDag'),
              // copyBag valid payload is an array of [passable, count] tuples
              // in which each passable is unique.
              fc.uniqueArray(
                fc.tuple(tie('arbDag'), fc.bigInt()),
                { selector: entry => entry[0] },
              ),
            ),
          }),
          fc.record({
            type: fc.constantFrom('copyMap'),
            payload: fc.oneof(
              tie('arbDag'),
              // copyMap valid payload is a {keys: Array<Passable>, values: Array<Passable>} record
              // in which keys are unique and both arrays have the same length.
              fc
                .uniqueArray(
                  fc.record({ key: tie('arbDag'), value: tie('arbDag') }),
                  { selector: entry => entry.key },
                )
                .map(entries => ({
                  keys: entries.map(({key}) => key),
                  values: entries.map(({value}) => value),
                })),
            ),
          }),
        )
```

2022-10-04 18:35 UTC, gibson042 commented on packages/store/tools/arb-passable.js
> +        { maxKeys: 3 },
The improvements for recursive arbitraries also allow us to remove these size constraints.
```suggestion
      fc.array(tie('arbDag')),
      fc.dictionary(
        arbString.filter(s => s !== 'then'),
        tie('arbDag'),
```

2022-10-04 18:35 UTC, gibson042 commented on packages/store/test/test-rankOrder.js
>        // operate on a set of three passables covering at least two ranks
```suggestion
      // operate on a set of three distinct passables covering at least two ranks
```

2022-10-08 04:41 UTC, erights commented on packages/store/tools/arb-passable.js
> +      },
I didn't really understand the explanation, but I took your advice. Done.

2022-10-08 04:45 UTC, erights commented on packages/store/tools/arb-passable.js
> +  fc.record({}),
I think I took this advice correctly but PTAL. I just moved the order around.

Resolving, but please unresolve if I misunderstood.

2022-10-08 04:56 UTC, erights commented on packages/store/tools/arb-passable.js
> +        )
Your new code is strictly better, so I took that. But copySet, copyBag, and copyMap also insist that their keys be reverse sorted, so we should eventually add some of those. Resolving with your change + added TODOs.

2022-10-08 04:58 UTC, erights commented on packages/store/tools/arb-passable.js
> +        { maxKeys: 3 },
Done.

2022-10-08 05:00 UTC, erights commented on packages/store/test/test-rankOrder.js
>        // operate on a set of three passables covering at least two ranks
Done.

2022-10-08 05:02 UTC, erights commented
Took all your suggestions. PTAL

2022-10-11 00:51 UTC, erights commented
ping

2022-10-13 19:44 UTC, erights commented
ping

2022-10-18 17:17 UTC, gibson042 approved these changes
LGTM!

2022-10-19 00:55 UTC, merged