fix: rename from FarClass to ExoClass, etc
Agoric/Agoric pull request #6323
Opened 2022-09-25 23:52 UTC by erights

Having failed to reopen https://github.com/Agoric/agoric-sdk/pull/6118 in place, I'm reopening as a new branch/PR

I failed apparently because I had already force pushed? See https://github.com/Agoric/agoric-sdk/pull/6118#issuecomment-1257312629

From https://github.com/Agoric/agoric-sdk/pull/6118 :
----
Staged on https://github.com/Agoric/agoric-sdk/pull/6107

Addresses https://github.com/endojs/endo/issues/1193 , but more narrowly

@dtribble and I were brainstorming name alternatives to `FarClass` (which we both hate for somewhat different reasons). There are three salient differences from normal object programming, where `FarClass` only suggests the first and third. 
   * It is a remotable, meaning it is exposed to messages from outside the vat (hence "Far")
   * Related, it is protected by an interfaceGuard that does the first phase type-like phase of input validation
   * It is programmed in a class-like manner, with inline methods in the concise-method syntax, accepting their instance-specific access via their `this` binding (hence "Class")

We also need to name the instance case, and `FarInstance` is way too awkward. The instance case has the first two features but not the third.

New aha: "Exo" does double duty. 
   * As a prefix meaning "outside", it suggests the remotable meaning. That was why I suggested Exo in the first place.
   * It lets us introduce the metaphor of the [ExoSkeleton](https://en.wikipedia.org/wiki/Exoskeleton) without being confused with the exoskeleton itself. "An exo is a creature with an exoskeleton" is a memorable explanation, even if there is no RL noun "Exo".

Also
   * It is short, so for the class case "ExoSkeleton" still works.
   * It is distinct from our current "Far" and so the "Instance" qualifier isn't needed for the protective instance case.

But this last bullet (distinct from "Far") means that it isn't an answer to our first search for a term, since it doesn't cover remotable objects without a protective exoskeleton (currently, "Far objects" and "remote presences"). Oh well. I think the rename is still worth it. 

---

Reviewers, I look forward to your impressions in the review comments.

If this PR meets with your approval soon, we could merge it into https://github.com/Agoric/agoric-sdk/pull/5960 before merging https://github.com/Agoric/agoric-sdk/pull/5960 into master, skipping a phase where we're using the wrong names on master.

2022-10-11 21:17 UTC, kriskowal approved these changes
Looks mechanical to me. I’m warming to the idea that this name change is a net improvement and, stew as I have on this question for long enough, have not found a more positive improvement.

2022-10-11 21:20 UTC, kriskowal commented
Caveat: this appears to be a breaking change and I do not know how it affects upgrade. However, the commit message should be framed like:

```
refactor(ertp)!: Rename etc

*BREAKING CHANGE*: How to update dependencies
```

This will ensure that Lerna generates a changelog and the appropriate version bumps.

2022-10-19 01:25 UTC, erights commented
See previous discussion at https://github.com/Agoric/agoric-sdk/pull/6118
See table of options at https://docs.google.com/spreadsheets/d/1yhKgzMOfmZOTnvP3Bh4p16H9RyYq_WhOlxZ3Qicx_Oc/edit#gid=0

2022-12-13 16:14 UTC, gibson042 approved these changes
I think "Exo" is a big improvement over "Far", and even the isolated noun usage works pretty well.

2023-01-20 07:29 UTC, erights commented
Please look at https://github.com/Agoric/agoric-sdk/pull/6818 for another candidate. I think I like that one better.

2023-01-21 00:23 UTC, turadg requested changes
+1 to the change of `vivify` to `prepare`. I concur with the rationale.

*decision process and rationale documented for posterity*

> Well, the message at the top of this PR does state a rationale. Yes, if this moves forward, this rationale should move to a more discoverable place.

I request that any PR that changes the names include the documentation within it. E.g. a Markdown file in `@agoric/store`.

*just enough complexity for new app programmers*

> IMO not worse than any of the other suggestions, and slightly better for the reasons stated in the rationale above.

Perhaps not worse but I don't think we're at the right names yet.

> Although similar to classes, these are different enough that it may be more confusing than clarifying to use the term "class"

This hasn't been my experience. I expect more confusion from "Factory" since it's a term often used for the business logic (e.g. vaultFactory, walletFactory) and not the runtime primitives.

`define…` to `make…Maker` imo is a regression in naming because it requires tracking the levels of "make". 

I request that the `prepare` change be pushed in a separate PR and proceed, and that the "Far" terminology get more discussion. Perhaps in a call. A product of that meeting could be the documentation I also am requesting :)

2023-01-21 00:56 UTC, turadg approved these changes
This simple change looks good to me. As I wrote on https://github.com/Agoric/agoric-sdk/pull/6323#pullrequestreview-1264534582 I ask that the naming rationale be documented within the codebase. E.g. `packages/store/docs/terminology.md`.

2023-01-21 12:07 UTC, merged