fix: step towards stratifying customDetails
Agoric/Agoric pull request #7080
Opened 2023-02-26 03:06 UTC by erights

Staged on #7067 , but intended as a more compat bridge to migrate to #7067 , once all occurrences of the deprecated spread customDetails have been removed.

2023-02-27 20:04 UTC, Chris-Hibbert requested changes
Looks good. Some changes requested.

2023-02-27 20:04 UTC, Chris-Hibbert commented on packages/swingset-runner/demo/zoeTests/vat-dave.js
> +      assert(typeof customDetails === 'object');
Why not move this above lines 90 and 92 and use this name there as well.

2023-02-27 20:04 UTC, Chris-Hibbert commented on packages/zoe/src/zoeService/zoeStorageManager.js
> +          // If the contract-provided `customDetails` include the properties
After #7067, this paragraph will no longer be needed, right?

2023-02-27 20:04 UTC, Chris-Hibbert commented on packages/zoe/src/zoeService/zoeStorageManager.js
> +                  customDetails,
If #7067 isn't expected to be merged immediately, there should be a TODO here referencing that change.

2023-02-27 20:04 UTC, Chris-Hibbert commented on packages/zoe/test/unitTests/contracts/test-callSpread.js
> +  assert(typeof customDetails === 'object');
Would it make sense for Zoe to export an `assertCustomDetails()` function to be used in all these places? For now, it could contain a `mustMatch()` clause that asserts it's an object, but if we nailed down the semantics of a particular keyword within `customDetails`, `assertCustomDetails()` could additionally enforce that.

... actually, can't `getInvitationDetails()` enforce that, so the clients don't have to check?

2023-02-28 01:56 UTC, erights commented on packages/swingset-runner/demo/zoeTests/vat-dave.js
> +      assert(typeof customDetails === 'object');
These are two different `customDetails`: this one is from `optionValue[0]` and the ones above from `invitationValue[0]`. But I took the suggestion anyway, making them stylistically consistent using distinct names.

Done.

2023-02-28 02:09 UTC, erights commented on packages/zoe/src/zoeService/zoeStorageManager.js
> +          // If the contract-provided `customDetails` include the properties
Good catch! I just removed it from #7067 . Done there.

2023-02-28 02:11 UTC, erights commented on packages/zoe/src/zoeService/zoeStorageManager.js
> +                  customDetails,
Done

2023-02-28 02:20 UTC, erights commented on packages/zoe/test/unitTests/contracts/test-callSpread.js
> +  assert(typeof customDetails === 'object');
I made the property optional, so only invitationDetails that have non-empty customDetails have the property at all. Then I had to type is as optional in InvitationDetails. What would `getInvitationDetails` do that would be helpful?

The `assert(typeof` is only to let the type checker know that I know it is an object.

2023-02-28 03:36 UTC, erights commented
PTAL

2023-02-28 17:11 UTC, Chris-Hibbert commented on packages/zoe/test/unitTests/contracts/test-callSpread.js
> +  assert(typeof customDetails === 'object');
> The assert(typeof is only to let the type checker know that I know it is an object

Understood. too bad it looks like it's trying to do more than that. okay.

2023-02-28 17:16 UTC, Chris-Hibbert approved these changes
LGTM

2023-02-28 17:36 UTC, erights commented on packages/zoe/test/unitTests/contracts/test-callSpread.js
> +  assert(typeof customDetails === 'object');
Cool. Resolving.

2023-02-28 18:15 UTC, merged