7099 debt terminology
Agoric/Agoric pull request #7137
Opened 2023-03-09 00:23 UTC by turadg

closes: #7099 

## Description

Vaults and Stakes have debts but the term "loan" is misleading. This replaces it it with "vault", "debt" and other more explicit terminology.

### Security Considerations

n/a

### Scaling Considerations

n/a

### Documentation Considerations

This updates documentation. Some external documentation may need updating too. cc @Tyrosine22 

### Testing Considerations

CI

2023-03-09 18:15 UTC, Chris-Hibbert requested changes
Lots of very local changes that will interact with #7047.  Can it wait?

2023-03-09 18:15 UTC, Chris-Hibbert commented on packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
> +    AmountMath.isEqual(newDebt, toMint) || Fail`debt fee mismatch`;
The fee is a `mintFee`. Wouldn't it be better to use that terminology?

2023-03-09 18:15 UTC, Chris-Hibbert commented on packages/inter-protocol/test/attestation/exampleLoanUsage.js
> + * RUN that can be vaulted is about 10% of the value of BLD represented
no way.

'lent', perhaps.  The README says the protocol 'lends' on the basis of collateral.  I think 'loaned' is acceptable.

You could also say that the amount that can be 'withdrawn' is limited.

2023-03-09 18:15 UTC, Chris-Hibbert commented on packages/inter-protocol/test/vaultFactory/test-vault-collateralization.js
> +  // ...so we can't take the same debtout
```suggestion
  // ...so we can't take the same debt out
```

2023-03-09 18:15 UTC, Chris-Hibbert commented on packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
> +  const debt = run.make(270n);
`borrowedAmount` would be better. `debt` includes the fee.

2023-03-09 18:15 UTC, Chris-Hibbert commented on packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
> +  // PriceAuthority's initial quote is 180. The max vault on 4 Aeth would be 600
vault's the wrong word here. maybe `borrowed`?

2023-03-09 18:15 UTC, Chris-Hibbert commented on packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
> +  const debt = run.make(370n);
`borrowedAmount`

2023-03-09 18:15 UTC, Chris-Hibbert commented on packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
> +  trace('0. Take out vault');
```suggestion
  trace('0. Create vault');
```

2023-03-09 18:15 UTC, Chris-Hibbert commented on packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
> +// Bob will also take out a vault and will give her the proceeds.
```suggestion
// Bob will also create a vault and will give her the proceeds.
```

2023-03-09 18:30 UTC, turadg commented on packages/inter-protocol/test/attestation/exampleLoanUsage.js
> + * RUN that can be vaulted is about 10% of the value of BLD represented
hehe this was find-replace. I'll use one of your suggestions.

2023-03-09 18:32 UTC, turadg commented
> Lots of very local changes that will interact with #7047. Can it wait?

ok. I'll put it with https://github.com/Agoric/agoric-sdk/pull/7094 in the queue of things to hold until after 7047.

2024-05-02 23:42 UTC, turadg commented
quite obsolete

2024-05-02 23:42 UTC, closed without merging