improve error thrown during collection.get(missingRemotable)
Agoric/Agoric pull request #7233
Opened 2023-03-23 20:57 UTC by warner

Previously, doing a virtualCollection.get() on a Remotable that was not present in the Map or Set would trigger an internal assertion (complaining about a "missing ordinal"), rather than reaching the usual error message (which includes the collection's label as a debugging aid).

This fixes the `get()` path for both maps and sets to check for ordinal-less Remotables first, before attempting to convert the key into a dbKey. This let us signal the right error message.

closes #7231

2023-03-23 23:26 UTC, FUDCo approved these changes
Good fix but I have some whinges about coding style.  But no need to re-review if you fix those.

2023-03-23 23:26 UTC, FUDCo commented on packages/swingset-liveslots/src/collectionManager.js
> +        throw Fail`key ${key} not found in collection ${q(label)}`;
I really don't like `if` without brackets around the consequent.  Shouldn't eslint complain about this?
And also don't like the `if` consequent on the same line with the `if`.

2023-03-23 23:26 UTC, FUDCo commented on packages/swingset-liveslots/src/collectionManager.js
> +        throw Fail`key ${key} not found in collection ${q(label)}`;
ditto

2023-03-23 23:26 UTC, FUDCo commented on packages/swingset-liveslots/src/collectionManager.js
> +      if (!result) throw Fail`key ${key} not found in collection ${q(label)}`;
Ditto.

2023-03-23 23:30 UTC, erights requested changes
Thanks for doing this!

2023-03-23 23:30 UTC, erights commented on packages/swingset-liveslots/src/collectionManager.js
> +      if (!result) throw Fail`key ${key} not found in collection ${q(label)}`;
```suggestion
      if (!result) {
        throw Fail`key ${key} not found in collection ${q(label)}`;
      }
```

2023-03-23 23:30 UTC, erights commented on packages/swingset-liveslots/src/collectionManager.js
> +        throw Fail`key ${key} not found in collection ${q(label)}`;
```suggestion
      if (passStyleOf(key) === 'remotable' && getOrdinal(key) === undefined) {
        throw Fail`key ${key} not found in collection ${q(label)}`;
      }
```

Don't our lint rules already prevent this? If not, can we get them to?

2023-03-23 23:49 UTC, warner commented on packages/swingset-liveslots/src/collectionManager.js
> +        throw Fail`key ${key} not found in collection ${q(label)}`;
Ok, I'll change that. I was trying for something concise and readable (what I really want is `assert.equal`, but `tsc` doesn't realize that surviving `assert.equal` means the type has been narrowed). Adding the extra braces feels like distraction to me, but I appreciate the safety arguments. (our eslint does not complain about the missing curlies; apparently it's a Jessie rule, but not applied to our normal style checks).

I dislike the same-line format too. `prettier` changed my two-line form to the one-line form.

2023-03-24 00:18 UTC, erights approved these changes
LGTM

2023-03-24 01:28 UTC, merged