first pass addition of serializeBodyFormat: smallcaps
Agoric/Agoric pull request #7565
Opened 2023-05-01 17:45 UTC by warner

refs #6822

2023-05-01 19:27 UTC, dckc commented on packages/deploy-script-support/src/code-gen.js
> +const { serialize } = makeMarshal(undefined, undefined, { serializeBodyFormat: 'smallcaps' });
This one should not use smallcaps.

2023-05-01 23:32 UTC, warner commented
tests are still failing in:
* quick:
  * governance: chip
  * others after governance?
* vats: warner
* lint
* solo
* inter-protocol
* quick2:
  * wallet/api
  * others after wallet/api?

2023-05-03 01:03 UTC, warner commented
I got packages/vats working with that last commit

2023-05-03 05:55 UTC, erights requested changes
Please switch to the approach illustrated at https://github.com/endojs/endo/blob/master/packages/marshal/test/test-marshal-testing.js unless there's a reason not to. It would do much less violence to the existing tests.

2023-05-03 15:04 UTC, warner commented
abandoned in favor of #7585, which does much less violence to the existing tests

2023-05-03 15:04 UTC, closed without merging