Correct for premature creation of provision account during upgrade
Agoric/Agoric pull request #7630
Opened 2023-05-05 23:29 UTC by JimLarson

closes: #7622

## Description

The provision account is unlike other module accounts in that it is exempted from the list of `x/bank` blocked addresses, so that it can receive ordinary transfers from other accounts. However, this runs the risk that if a transfer happens before the provision account is used as a module account, it will be created as the default account type, not a module account.

This appears to have happened on mainnet, so we should fix it as part of upgrade-10.

### Security Considerations

N/A

### Scaling Considerations

N/A

### Documentation Considerations

N/A

### Testing Considerations

The underlying problem still exists for any freshly-created networks. Tests will need to force the creation of the provision account as a module account before transferring funds to it.

2023-05-06 17:42 UTC, michaelfig commented
> The underlying problem still exists for any freshly-created networks. Tests will need to force the creation of the provision account as a module account before transferring funds to it.

As I mentioned in private chat, we can protect freshly-created networks via:
> calling `vbankKeeper.GetModuleAccountAddress(ctx, vbanktypes.ProvisionPoolName)` at agd start (probably in `app.go`).  It’s idempotent.

2023-05-06 17:44 UTC, michaelfig requested changes
This code looks good, but I'd like the PR to also implement https://github.com/Agoric/agoric-sdk/pull/7630#issuecomment-1537189562 for completeness.

Thanks!

2023-05-07 01:36 UTC, JimLarson commented
Added logic to create the provision account at genesis time. Put it all in `app.go`, so it's contained alongside the blocked account policy exception which makes the creation/migration necessary.

2023-05-07 01:57 UTC, michaelfig approved these changes

2023-05-07 03:23 UTC, merged