Improve checkKeys error message
Agoric/Agoric pull request #797
Opened 2020-03-27 19:58 UTC by DavidBruant

2020-03-27 20:09 UTC, katelynsills approved these changes
Looks good to me. thanks!

2020-03-27 20:09 UTC, katelynsills approved these changes
Oh actually let's make sure the tests pass

2020-03-27 20:11 UTC, katelynsills requested changes
Sorry, this should be "request changes" because the tests aren't passing

2020-04-01 08:17 UTC, katelynsills commented
I think this just has linting errors. If we fix those, we can merge

2020-04-03 16:48 UTC, Chris-Hibbert commented on packages/zoe/src/cleanProposal.js
> +      details`key ${key} was not one of the expected keys (${expectedKeys.join(', ')})`,
```suggestion
      details`key ${key} was not one of the expected keys (${expectedKeys.join(
        ', ',
      )})`,
```

2020-04-03 16:48 UTC, Chris-Hibbert approved these changes
eslint wanted a change in the format, but otherwise, this looks like an improvement.

2020-04-06 02:15 UTC, katelynsills commented
@DavidBruant I'd love to merge this. Do you think we could fit it in this week?

2020-04-06 11:05 UTC, DavidBruant commented
yes; i'll fix the conflict

2020-04-07 08:59 UTC, DavidBruant commented
Things moved after the sparse keyword PR
I'm closing this PR in favor of #873

2020-04-07 08:59 UTC, closed without merging