refactor(x/swingset): Consolidate swingset message definition and initialization
Agoric/Agoric pull request #8676
Opened 2023-12-19 22:29 UTC by gibson042

## Description

Defines context-derived `blockHeight` and `blockTime` and (most importantly) an interface-derived `type` for the JSON serialization of all "action" messages headed towards swingset in one place rather than in disjoint type definitions scattered throughout the code.

Alternatively, the `type` values could be defined even closer to individual structs by means of reflection[^1] or [custom `MarshalJSON` methods](https://pkg.go.dev/encoding/json#example-package-CustomMarshalJSON)[^2]. But I feel like this approach strikes the right balance for now.

[^1]:
    [e.g.](https://go.dev/play/p/swB0cc3qFUU), ``` type walletSpendAction struct { Type string `json:"type" default:"WALLET_SPEND_ACTION"`; … } ``` with
    ```go
    if typeField, ok := reflect.TypeOf(action).Elem().FieldByName("Type"); ok {
    	action.Type = typeField.Tag.Get("default")
    }
    ```
[^2]:
    [e.g.](https://go.dev/play/p/0OkZE9WSjTE), ``` type walletSpendAction struct { Type walletSpendType `json:"type"`; … } ``` with
    ```go
    type walletSpendActionType struct{}
    func (_ *walletSpendActionType) MarshalJSON() ([]byte, error) { return []byte(`"WALLET_SPEND_ACTION"`), nil }
    ```

### Security Considerations

n/a

### Scaling Considerations

n/a

### Documentation Considerations

This should help anyone looking at either the Go or JS side of SwingSet messaging better correlate I/O with the other side.

### Testing Considerations

n/a

### Upgrade Considerations

n/a

2023-12-20 16:34 UTC, michaelfig reviewed
I'm happy you're considering changes like this, but `x/swingset` isn't the only place that uses Actions.  Is it possible to go further and improve the signature of `vm.ActionPusher` to accept only Actions (instead of `interface{}`)?  That would reveal which other packages are relying on `ActionPusher`.  Then, I hope something like the reflection approach could be used in the `ActionPusher` implementations.

2023-12-20 16:34 UTC, michaelfig commented on golang/cosmos/x/swingset/keeper/msg_server.go
> +func finishAction[T *deliverInboundAction | *walletAction | *walletSpendAction | *provisionAction | *installBundleAction](action T, ctx sdk.Context) T {
Please put context first, following the existing convention of other contextual functions:
```suggestion
func finishAction[T *deliverInboundAction | *walletAction | *walletSpendAction | *provisionAction | *installBundleAction](ctx sdk.Context, action T) T {
```

2023-12-20 17:05 UTC, michaelfig commented
I found [a hint](https://stackoverflow.com/a/23046869) using MarshalJSON that may be relevant.

2024-01-03 02:00 UTC, JimLarson commented
As @michaelfig mentioned, we have actions in several other modules, so a `switch` statement that enumerates all the possible actions is too non-modular. As in conventional OO programming, you usually use a base class to avoid the giant type switch - the Go equivalent would be to define an interface.

I'm on board with the `ActionMeta` (consider `ActionHeader` instead) to remove redundancy and enforce consistency in the structure definitions, along with a method to populate the block height/time from a `sdk.Context`. I'm guessing you're looking for a more automated way to do the `Type` field as well.

A simple way to handle types would to declare an interface with a `GetType() string` method. You then put this code in a common place like the `vm` package.

```
type ActionI interface {
    GetHeader() *ActionMeta
    GetType() string
}

func Populate(ctx sdk.Context, a ActionI) {
    header := a.getHeader()
    header.Type = a.GetType()
    header.BlockHeight = ctx.BlockHeight()
    header.BlockTime = ctx.BlockTime()
}

// This defines GetHeader() for anything that embeds *ActionMeta
func (am *ActionMeta) GetHeader() *ActionMeta {
    return am
}
```

then this code goes in a module that defines actions:

```
type walletSpendAction struct {
    *vm.ActionMeta
    Owner       string `json:"owner"`
    SpendAction string `json:"spendAction"`
}

var _ vm.ActionI = &walletSpendAction{} // compile-time check that it implements the interface

func (wsa walletSpendAction) GetType() string {
    return "WALLET_SPEND_ACTION"
}

func (keeper msgServer) WalletSpendAction(goCtx context.Context, msg *types.MsgWalletSpendAction) (*types.MsgWalletSpendActionResponse, error) {
    ...
    action := &walletSpendAction{
        // only populate the fields specific to this action
        Owner:       msg.Owner.String(),
        SpendAction: msg.SpendAction,
    }
    vm.Populate(ctx, action) // populate the common fields
    ...
}
```

But this has the disadvantage that you might cut-and-paste one action definition as a template for another and accidentally use the same type string. The type-switch form makes such a mistake more visible, but still doesn't provide a guarantee at either compile or run-time.

At the cost of a little more complexity, we can have an initialization-time check that strings are unique. The `vm` package would, possibly using reflection, populate a map of type names to prototype objects, and a reverse map, then update the `Populate` function to use these maps. A module that implements an action would skip the `GetType()` method and register its types at init-time:

```
init (
    vm.RegisterAction(&walletAction{}, "WALLET_ACTION")
    vm.RegisterAction(&walletSpendAction{}, "WALLET_SPEND_ACTION")
    ...
)
```

This is already a precedent for needing to register various structures, e.g. for the `sdk.Msg` types.

Or, you could skip automating the type names as not being worth the complexity.

2024-01-03 02:01 UTC, JimLarson requested changes
Please see the lengthy PR comment for some big-picture feedback.

2024-01-03 02:01 UTC, JimLarson commented on golang/cosmos/x/swingset/keeper/msg_server.go
> +type walletAction struct {
Please keep `walletAction` and the rest where they were, so each definition can be close to the code that uses it (and minimizing the diff).

2024-01-06 00:58 UTC, closed without merging