fix(agoric-cli): handle another vstorage error variation
Agoric/Agoric pull request #9024
Opened 2024-03-02 00:45 UTC by dckc

avoid:

```
Error#1: error code 18 reading data of published.wallet.agoric1l...: failed to load state at height 14007...; version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height (latest height: 14026...): invalid request

  at packages/agoric-cli/src/lib/rpc.js:83:23
  at async Object.readAt (packages/agoric-cli/src/lib/rpc.js:122:19)
  at async Object.readFully (packages/agoric-cli/src/lib/rpc.js:144:38)
  at async storedWalletState (packages/agoric-cli/src/lib/wallet.js:228:21)
  at async Promise.all (index 1)
  at async
  Command.<anonymous> (packages/agoric-cli/src/commands/inter.js:566:34)
```

closes: #XXXX
refs: #XXXX

## Description

### Security Considerations

### Scaling Considerations

### Documentation Considerations

### Testing Considerations

### Upgrade Considerations

2024-03-02 00:51 UTC, dckc commented
hm... maybe I forgot to `yarn build` or something?

```
$ AGORIC_NET=main inter bid list --from agoric1l...
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/connolly/projects/agoric-sdk/node_modules/@agoric/cosmic-proto/dist/codegen/index.js' imported from /Users/connolly/projects/agoric-sdk/packages/agoric-cli/src/lib/chain.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:327:11)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

2024-04-03 02:45 UTC, otoole-brendan commented
@aj-agoric let's figure out a plan to expedite getting this deployed if it doesn't need a chain-halting upgrade. Users can't see their bids in CLI until this fix is deployed

2024-04-03 04:24 UTC, dckc commented
@gibson042 I just added some questions to the PR description. Would you let me/us know what you think about them, please?

2024-04-09 19:20 UTC, gibson042 requested changes

2024-04-09 19:20 UTC, gibson042 commented on packages/agoric-cli/src/lib/rpc.js
> +            err.message.match(/pruned/)
Ugh, I was really hopeful about **abandoning** error message scans. In this case, the "_failed to load state at height_" text comes from [`func (app *BaseApp) createQueryContext`](https://github.com/agoric-labs/cosmos-sdk/blob/76e151914572fbefb0a6c7ebef1b51d464a9fcbe/baseapp/abci.go#L687-L694), which wraps the "_version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height_" text from [`func (st *Store) GetImmutable`](https://github.com/agoric-labs/cosmos-sdk/blob/76e151914572fbefb0a6c7ebef1b51d464a9fcbe/store/iavl/store.go#L114) via [`func (rs *Store) CacheMultiStoreWithVersion`](https://github.com/agoric-labs/cosmos-sdk/blob/76e151914572fbefb0a6c7ebef1b51d464a9fcbe/store/rootmulti/store.go#L497) and unfortunately associates it with an "invalid request" error code. I have opened https://github.com/cosmos/cosmos-sdk/issues/19992 for that issue, and in the meantime I guess we want a corresponding update here.
```suggestion
            // CosmosSDK ErrInvalidRequest with particular message text;
            // misrepresentation of pruned data
            // TODO replace after incorporating a fix to
            // https://github.com/cosmos/cosmos-sdk/issues/19992
            (err.codespace === 'sdk' && err.code === 18 && err.message.match(/pruned/))
```

2024-04-22 16:57 UTC, gibson042 approved these changes

2024-04-22 18:09 UTC, dckc commented
glitch, I hope:

```
lerna ERR! E503 one of the uplinks is down, refuse to publish
```
-- [ci log #30969](https://github.com/Agoric/agoric-sdk/actions/runs/8787948814/job/24114351101?pr=9024)

2024-04-22 18:18 UTC, merged