protobufs for Cosmos
Agoric/Agoric pull request #9181
Opened 2024-04-01 21:38 UTC by turadg

refs: #9111

## Description

Extracted from https://github.com/Agoric/agoric-sdk/pull/9112 while I try to get the rest of that working.

This make `@agoric/cosmic-proto` keep all the protobufs it builds in its own tree in SCM. Previously it would copy them just-in-time from cosmic-swingset but that made it more complicated to handle third party protos that aren't part of cosmic-swingset. It still copies over the latest before building. There's a separate tasks to ensure SCM is up to date: https://github.com/Agoric/agoric-sdk/issues/8131

This also simplifies the Telescope config and tooling output.

### Security Considerations

no change
### Scaling Considerations
no change

### Documentation Considerations
no change

### Testing Considerations
no change

### Upgrade Considerations
fully backwards compatible

2024-04-02 21:01 UTC, JimLarson commented
Initial feedback not tied to any particular file location:

- Please add to the PR description what was done to obtain the proto files and generate the generated code.
- Please update `MAINTAINERS.md` to ensure that it's up-to-date and that you followed its process.
- Please add a tiny `MAINTAINERS.md` in `golang/cosmos` to just say that when any Agoric protos are changed, or when we update cosmos-sdk, we should re-import per `packages/cosmic-proto/MAINTAINERS.md`.

We have #9018 to see if we can use `buf` to automate some of this, but for now this is great.

I'll spot-check some of the protos to ensure they're the right versions.

2024-04-02 21:25 UTC, JimLarson requested changes
See conversation.

2024-04-02 22:00 UTC, JimLarson requested changes, later dismissed

2024-04-02 22:00 UTC, JimLarson commented on packages/cosmic-proto/proto/amino/amino.proto
> +}
Missing newline at EOF.

2024-04-02 22:00 UTC, JimLarson commented on packages/cosmic-proto/proto/cosmos/crypto/hd/v1/hd.proto
> +syntax = "proto3";
It's missing the [first line](https://github.com/cosmos/cosmos-sdk/blob/7799bba7bc889288607576aa11655b5fc31a2da9/proto/cosmos/crypto/hd/v1/hd.proto#L1) of the version from cosmos-sdk 0.46.16.

A trivial difference to be sure, but it just makes me uncertain whether these protos were copied from the right place. I'll await the previously-requested info about where these came from.

2024-04-03 21:59 UTC, turadg commented on packages/cosmic-proto/proto/amino/amino.proto
> +}
done

2024-04-03 22:01 UTC, turadg commented
> * Please update `MAINTAINERS.md` to ensure that it's up-to-date and that you followed its process.
good catch, done

> * Please add to the PR description what was done to obtain the proto files and generate the generated code.

Now in MAINTAINERS

> * Please add a tiny `MAINTAINERS.md` in `golang/cosmos` to just say that when any Agoric protos are changed, or when we update cosmos-sdk, we should re-import per `packages/cosmic-proto/MAINTAINERS.md`.

Done. I referenced https://github.com/Agoric/agoric-sdk/issues/8131 that @ivanlei has volunteered to take on.

2024-04-04 17:10 UTC, kriskowal commented on packages/cosmic-proto/proto/cosmos/base/reflection/v2alpha1/reflection.proto
> +// Since: cosmos-sdk 0.43
Do we need an annotation here to indicate that these are copies, to avoid confusion when they’re overwritten?

2024-04-04 17:10 UTC, kriskowal commented on golang/cosmos/MAINTAINERS.md
> +https://github.com/Agoric/agoric-sdk/issues/8131 will help automate updating protos, but not the publishing to NPM of the codegen-ed JS utilities for working with the APIs they define.
Can we verify they’re in sync with CI?

2024-04-04 17:12 UTC, kriskowal commented on golang/cosmos/MAINTAINERS.md
> +https://github.com/Agoric/agoric-sdk/issues/8131 will help automate updating protos, but not the publishing to NPM of the codegen-ed JS utilities for working with the APIs they define.
I see https://github.com/Agoric/agoric-sdk/issues/8131

2024-04-04 17:12 UTC, kriskowal approved these changes

2024-04-04 17:33 UTC, turadg commented on packages/cosmic-proto/proto/cosmos/base/reflection/v2alpha1/reflection.proto
> +// Since: cosmos-sdk 0.43
It's a good thought. I expect the person doing the overwriting will be familiar with MAINTAINERS.md so not be confused, and if they do get confused they will read the docs

2024-04-04 18:10 UTC, merged

2024-04-04 21:05 UTC, JimLarson commented
Thanks for the updates to MAINTAINERS. I'm still a little uneasy with the tiny, trivial differences between the proto files obtained from NPM and the proto files obtained from github. If we start relying on `buf`, there's a third source with its own possible variations. However, the differences are so-far trivial, and protobuf should be quite tolerant of version skew among any responsible history of proto publications, so this merge is fine. I think we can take another look at fine-tuning the procedure and minimizing the differences in #9018 and I can take a swing and running these procedures.