refactor(xsnap): Cleanup build.js
Agoric/Agoric pull request #9674
Opened 2024-07-09 22:53 UTC by gibson042

Ref #9614
Ref #9618

## Description
Simplifies and documents functions. See individual commits for details.

### Security Considerations
None.

### Scaling Considerations
n/a

### Documentation Considerations
Includes JSDoc improvements.

### Testing Considerations
None.

### Upgrade Considerations
n/a

2025-02-11 16:02 UTC, siarhei-agoric commented on packages/xsnap/src/build.js
>          stdio: ['inherit', 'pipe', 'inherit'],
I know this is not a part of the change, but I do not think that default `inherit` for child's stdin in general is a good idea, as it opens up a possibility for the child to [perhaps erroneously] steal input which is intended for the parent. I think `ignore` should be the default if there is no explicit expectation of some specific child-parent communication coordination protocol.

2025-02-13 17:35 UTC, gibson042 commented on packages/xsnap/src/build.js
>          stdio: ['inherit', 'pipe', 'inherit'],
It was safe in this case (and purely internal to the file), but you're right. And since there's no expectation of input for any of these git/make/npm commands, I went ahead and made the change.

2025-02-14 05:38 UTC, mhofman reviewed
I think this looks like a pure refactor but I'm not confident I'm following all the changes. My main concern is breakage in the case of yarn install of xsnap. I believe we have poor coverage of that case.

2025-02-14 15:59 UTC, gibson042 commented
> I think this looks like a pure refactor but I'm not confident I'm following all the changes. My main concern is breakage in the case of yarn install of xsnap. I believe we have poor coverage of that case.

@mhofman I just stepped through everything to re-convince myself, and came away satisfied... is there a commit thta I should break down further? The most intricate was https://github.com/Agoric/agoric-sdk/pull/9674/commits/4d4674d045303ca69cc82b12d74b032a75bdaf8b , which breaks down like so:

Given `hasBin`, `hasSource`, `hasGit`, `showEnv = args.includes('--show-env');`, and `isWorkingCopy = hasGit || (!hasSource && !hasBin);`...

<table>
<thead><tr><th>old <code>main</code> behavior</th><th>old <code>main</code> behavior</th></tr></thead>
<tbody><tr>
<td>

* If `showEnv`, then
  1. Assert `isWorkingCopy`.
  2. `updateSubmodules(showEnv, …)`.
  3. \<implicit `return`>
* If `isWorkingCopy`, then
  1. `updateSubmodules(showEnv, …)`.
  2. Set `hasSource = true;`.
* If `hasSource`, then
  1. `force = await (!hasBin || isRejected(npm.run(…)));`.
  2. `buildXsnap(platform, force, …)`.
* Else if not `hasBin`, then
  1. `throw`.

</td>
<td>
  
1. If `args.includes('--show-env')`, then
   1. Assert `isWorkingCopy`.
   2. `updateSubmodules(true, …)`.
   3. `return`.
2. If `isWorkingCopy`, then
   1. `updateSubmodules(false, …)`.<br><br>
3. If `hasSource` or `isWorkingCopy`, then
   1. `force = await (!hasBin || isRejected(npm.run(…)));`.
   2. `buildXsnap(platform, force, …)`.
4. Else if not `hasBin`, then
   1. `throw`.

</td>
</tr></tbody>
</table>

2025-02-14 16:37 UTC, mhofman commented
> The most intricate was [4d4674d](https://github.com/Agoric/agoric-sdk/commit/4d4674d045303ca69cc82b12d74b032a75bdaf8b) , which breaks down like so

Yeah that was the one that I wasn't sure of the equivalence just starring at the code last night. With the added explanation and a fresh brain, I'll take another pass

2025-02-24 21:50 UTC, kriskowal approved these changes

2025-02-24 21:50 UTC, kriskowal commented on packages/xsnap/src/build.js
> +      // We discovered that in other cases, the prefix is a single space.
This looks like a `fix`.

2025-02-24 21:50 UTC, kriskowal commented on packages/xsnap/src/build.js
> -  // We build both release and debug, so checking for one should suffice.
Looks like we lose this lore, which we might need to reconstruct if we need to come up with different logic. Is it more confusing in this form than the commented logic?

2025-02-24 21:51 UTC, kriskowal commented
> I think this looks like a pure refactor but I'm not confident I'm following all the changes. My main concern is breakage in the case of yarn install of xsnap. I believe we have poor coverage of that case.

This can be manually verified with `npm pack`, then `npm postinstall` in the extracted `package` of the tarball. We could probably automate that test.

2025-02-24 22:01 UTC, kriskowal requested changes
Sorry for the retraction. Looking back, I conclude that it’s time for a `pack` and `postinstall` test.

2025-02-25 02:42 UTC, gibson042 commented on packages/xsnap/src/build.js
> +      // We discovered that in other cases, the prefix is a single space.
Nope, just a move (it was previously `parseStatus` in `makeSubmodule`). There is a notional difference in the `describe` component, but a) it doesn't actually come up in actual `git status` output, and b) we don't look for it anyway.

2025-02-25 02:53 UTC, gibson042 commented on packages/xsnap/src/build.js
> -  // We build both release and debug, so checking for one should suffice.
> Is it more confusing in this form than the commented logic?

For me, yes, especially with the actual logic being rather simple (`isWorkingCopy := hasGit || (!hasSource && !hasBin)`, `isWorkingCopy ⇒ updateSubmodules`, `hasSource || isWorkingCopy ⇒ buildXsnap` with `force := !hasBin || <check-version does not pass>`). But I can try restoring and correcting this if you prefer.

2025-03-02 21:39 UTC, dckc commented on packages/xsnap/src/build.js
> +    await showEnv(submodules, { git, stdout });
POLA :trophy:

2025-03-04 03:09 UTC, kriskowal approved these changes
@gibson042 I’ve landed https://github.com/Agoric/agoric-sdk/pull/9674 and rebased this PR so my approval is now only contingent on passing the new automated test.

2025-03-04 04:11 UTC, merged